/**
 * Parity harness (design doc §7.2): the TS port's output must structurally
 * equal the REAL Python source's output for identical input.
 *
 * `fixtures/parity/*.expected.json` were generated by running
 * `fixtures/parity/dump_python_papers.py` under
 * `uv run --extra dev python` (mocked `request_with_retry` / a canned
 * `requests` transport adapter for the arXiv client — no network), and are
 * committed so this test does not depend on Python being installed to run.
 * To regenerate them after a behavior change, re-run:
 *
 *   uv run --extra dev python apps/pipeline/test/collect/fixtures/parity/dump_python_papers.py
 *
 * and review the diff.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { paperToDict } from "../../src/collect/model/paper.js";
import { ArxivSource } from "../../src/collect/sources/arxiv/arxiv.js";
import { OpenAlexSource } from "../../src/collect/sources/openalex.js";
import { S2Source } from "../../src/collect/sources/s2.js";
import { diffJsonValues } from "../../src/parity/json-diff.js";
import type { JsonValue } from "../../src/parity/types.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "fixtures", "parity");

function readFixture(name: string): string {
  return readFileSync(join(FIXTURES, name), "utf8");
}

function readExpected(scenario: string): JsonValue {
  return JSON.parse(readFixture(`${scenario}.expected.json`)) as JsonValue;
}

interface ActualShape {
  papers: unknown[];
  truncatedKeywords: string[];
  degradedKeywords: readonly (readonly [string, string])[];
}

function toComparable(actual: ActualShape): JsonValue {
  return JSON.parse(
    JSON.stringify({
      degradedKeywords: actual.degradedKeywords.map(([kw, reason]) => [kw, reason]),
      papers: actual.papers.map((p) => paperToDict(p as Parameters<typeof paperToDict>[0])),
      truncatedKeywords: actual.truncatedKeywords,
    }),
  ) as JsonValue;
}

describe("parity: TS collect/ sources vs. real Python sources", () => {
  it("arxiv_happy", async () => {
    const body = readFixture("arxiv_happy.atom.xml");
    const src = new ArxivSource(
      { delaySeconds: 0 },
      { fetchText: async () => ({ status: 200, text: async () => body }) },
    );
    const result = await src.fetch({
      keywords: ["transformer"],
      categories: [],
      sinceDate: "2000-01-01",
      maxResults: 10,
    });
    const diffs = diffJsonValues(readExpected("arxiv_happy"), toComparable(result));
    expect(diffs).toEqual([]);
  });

  it("arxiv_truncated", async () => {
    const body = readFixture("arxiv_truncated.atom.xml");
    const src = new ArxivSource(
      { delaySeconds: 0 },
      { fetchText: async () => ({ status: 200, text: async () => body }) },
    );
    const result = await src.fetch({
      keywords: ["llm"],
      categories: [],
      sinceDate: "2026-01-01",
      maxResults: 3,
    });
    const diffs = diffJsonValues(readExpected("arxiv_truncated"), toComparable(result));
    expect(diffs).toEqual([]);
  });

  it("s2_happy", async () => {
    const body = JSON.parse(readFixture("s2_happy.json"));
    const src = new S2Source(
      { delaySeconds: 0 },
      { fetchImpl: async () => ({ status: 200, json: async () => body }) },
    );
    const result = await src.fetch({
      keywords: ["rag"],
      categories: [],
      sinceDate: "2026-01-01",
      maxResults: 10,
    });
    const diffs = diffJsonValues(readExpected("s2_happy"), toComparable(result));
    expect(diffs).toEqual([]);
  });

  it("s2_skip", async () => {
    const body = JSON.parse(readFixture("s2_skip.json"));
    const src = new S2Source(
      { delaySeconds: 0 },
      { fetchImpl: async () => ({ status: 200, json: async () => body }) },
    );
    const result = await src.fetch({
      keywords: ["kw"],
      categories: [],
      sinceDate: "2026-01-01",
      maxResults: 10,
    });
    const diffs = diffJsonValues(readExpected("s2_skip"), toComparable(result));
    expect(diffs).toEqual([]);
  });

  it("openalex_happy", async () => {
    const body = JSON.parse(readFixture("openalex_happy.json"));
    const src = new OpenAlexSource(
      { delaySeconds: 0 },
      { fetchImpl: async () => ({ status: 200, json: async () => body }) },
    );
    const result = await src.fetch({
      keywords: ["sample topic"],
      categories: [],
      sinceDate: "2026-01-01",
      maxResults: 10,
    });
    const diffs = diffJsonValues(readExpected("openalex_happy"), toComparable(result));
    expect(diffs).toEqual([]);
  });
});
