#!/usr/bin/env -S npx tsx
/**
 * Postbuild step: writes `apps/web/out/_redirects` (Cloudflare Pages).
 *
 * Why this exists (design doc §4.2-3): the current GitHub Pages site serves
 * `docs/<conf>/lineage.html`, `deep.html` and `paper-links.html` as real
 * files, while Next's static export writes those routes as
 * `<conf>/lineage/index.html` etc. With no `lineage.html` file in the output,
 * Pages cannot resolve the old URL on its own, so every external link and
 * bookmark to a `.html` path would 404 after the switch. These rules map the
 * old `.html` shapes onto the new directory URLs, 301, and Cloudflare keeps
 * the query string (`?q=`, `?theme=`, ...) and the fragment.
 *
 * `apps/web/out/_redirects` is a build artifact regenerated here -- the file
 * is replaced entirely on every run (append-safe), never hand-edited.
 *
 * Free-tier budget (design doc §1.1): 2,000 static + 100 dynamic rules.
 * Placeholder (`:name`) rules count as dynamic, so `renderRedirects()` is
 * asserted against that ceiling by test/misc/redirects.test.ts rather than
 * trusted.
 */
import { stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(SCRIPT_DIR, "..", "out");

/** Cloudflare Pages redirect line. Only 301s are generated here. */
export interface RedirectRule {
  readonly from: string;
  readonly to: string;
  readonly status: 301;
}

/** Ceiling on placeholder rules for the Cloudflare Pages free plan. */
export const DYNAMIC_RULE_LIMIT = 100;

/**
 * Old `.html` paths -> the directory URL Next actually writes. Evaluated in
 * order, so the scoped (`/:conf/...`) rules come before the site-wide one.
 */
export const LEGACY_HTML_RULES: readonly RedirectRule[] = [
  { from: "/:conf/lineage.html", to: "/:conf/lineage/", status: 301 },
  { from: "/:conf/deep.html", to: "/:conf/deep/", status: 301 },
  { from: "/:conf/paper-links.html", to: "/:conf/paper-links/", status: 301 },
  { from: "/:conf/index.html", to: "/:conf/", status: 301 },
  { from: "/index.html", to: "/", status: 301 },
];

/** A `:placeholder` rule is billed against the smaller (dynamic) quota. */
export function isDynamicRule(rule: RedirectRule): boolean {
  return rule.from.includes(":") || rule.to.includes(":");
}

export function dynamicRuleCount(rules: readonly RedirectRule[]): number {
  return rules.filter(isDynamicRule).length;
}

/** One rule as a `_redirects` line: `<from> <to> <status>`. */
export function renderRule(rule: RedirectRule): string {
  return `${rule.from} ${rule.to} ${rule.status}`;
}

/**
 * The whole `_redirects` file: a `#` comment header (ignored by Pages) that
 * records the rule counts against the free-plan budget, then one rule per
 * line, terminated by a newline.
 */
export function renderRedirects(rules: readonly RedirectRule[] = LEGACY_HTML_RULES): string {
  const dynamic = dynamicRuleCount(rules);
  const staticCount = rules.length - dynamic;
  const header = [
    "# Generated by apps/web/scripts/redirects.ts at postbuild. Do not hand-edit.",
    "# Old docs/*.html URLs -> the directory URL Next's static export writes.",
    `# Rules: ${staticCount} static, ${dynamic} dynamic of ${DYNAMIC_RULE_LIMIT} allowed.`,
  ].join("\n");
  return `${header}\n${rules.map(renderRule).join("\n")}\n`;
}

/** Fails loudly instead of writing next to a missing build output. */
async function assertOutDir(outDir: string): Promise<void> {
  try {
    const info = await stat(outDir);
    if (!info.isDirectory()) {
      throw new Error("not a directory");
    }
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    throw new Error(`${outDir} is not a build output directory (${reason}); run next build first`);
  }
}

async function main(): Promise<void> {
  await assertOutDir(OUT_DIR);
  const target = join(OUT_DIR, "_redirects");
  const dynamic = dynamicRuleCount(LEGACY_HTML_RULES);
  const summary = `${LEGACY_HTML_RULES.length} rule(s), ${dynamic} dynamic`;
  await writeFile(target, renderRedirects(), "utf8");
  console.log(`redirects: wrote ${target} (${summary} of ${DYNAMIC_RULE_LIMIT} allowed)`);
}

/**
 * `main()` is skipped when this module is imported (a Vitest test reads the
 * pure functions above). The sibling scripts (copy-data.ts, csp-hash.ts) run
 * unconditionally because nothing imports them; here, importing the real
 * generator is what makes the rule-count contract meaningful.
 */
function invokedAsScript(): boolean {
  const entry = process.argv[1];
  return entry !== undefined && resolve(entry) === fileURLToPath(import.meta.url);
}

if (invokedAsScript()) {
  main().catch((err: unknown) => {
    console.error(err);
    process.exitCode = 1;
  });
}
