#!/usr/bin/env -S npx tsx
/**
 * Postbuild step: writes `apps/web/out/sitemap.xml` from the pages the build
 * actually produced (`apps/web/scripts/sitemap.ts` replaces
 * `paperpilot/scripts/build_sitemap.py` for the Next output, design doc §8
 * P4b; the shape of the file is kept identical to `docs/sitemap.xml`).
 *
 * Inputs are the built `out/**\/index.html` files, so the sitemap can never
 * list a page that is not published:
 *   - `404` and Next's internal `_*` routes are excluded (the 404 page is the
 *     not-found fallback, served with HTTP 404 -- design doc §4.2-4);
 *   - a page whose own metadata says `noindex` is excluded, which is how the
 *     generated `paper-links` no-JS duplicates stay out;
 *   - every remaining page becomes `canonicalUrl(<dir-of-that-page>)`, so the
 *     origin and path prefix come from `@paperpilot/core` in exactly one
 *     place, never from a string written into this file.
 *
 * `out/sitemap.xml` is a build artifact: replaced entirely on every run,
 * never hand-edited. No `priority` / `changefreq` elements (search engines
 * ignore both) -- same decision as the current Python generator.
 */
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalUrl } from "../lib/config";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(SCRIPT_DIR, "..", "out");

/** One built page: its out-relative POSIX path and its HTML. */
export interface BuiltPage {
  readonly relPath: string;
  readonly html: string;
}

const XML_DECLARATION = '<?xml version="1.0" encoding="UTF-8"?>';
const URLSET_OPEN = '<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">';
const URLSET_CLOSE = "</urlset>\n";

/** Kept free of `--` runs: XML forbids them inside a comment. */
const HEADER_COMMENT = [
  "<!-- Generated by apps/web/scripts/sitemap.ts at postbuild. Do not hand-edit:",
  "     rebuild apps/web after adding a page. The built out pages are the only input,",
  "     so a page that is not published can never be listed here.",
  "",
  "     The 404 fallback, Next internal underscore routes, and any page whose own",
  "     robots meta says noindex are excluded (that is how the generated paper-links",
  "     no-JS duplicates stay out). Theme query variants share the theme page and are",
  "     never listed separately. A conference lineage, deep, or themes route is",
  "     listed only once lineage-quality-v1.json marks its collection ready and",
  "     passed (safety contracts CAT-39, ported from build_sitemap.py's",
  "     _eligible_lineage_routes); a missing or malformed manifest excludes every",
  "     one of them. URLs are absolute, from the one origin/prefix setting in",
  "     packages/core, and carry no priority or changefreq elements: search",
  "     engines ignore both. -->",
].join("\n");

interface LineageQualityRow {
  readonly kind?: unknown;
  readonly slug?: unknown;
  readonly conference?: unknown;
  readonly availability?: unknown;
  readonly audit_status?: unknown;
}

/**
 * Site-relative routes the lineage quality manifest authorises for the
 * sitemap, ported 1:1 from `paperpilot/scripts/build_sitemap.py`'s
 * `_eligible_lineage_routes` (safety contracts CAT-39): only `kind`
 * "conference" / "theme" / "deep" rows that are both `availability:
 * "ready"` and `audit_status: "passed"` become a route. `manifestRaw`
 * being unparseable, not an object, or missing a `collections` array
 * returns an empty set -- sitemap discovery is a publication boundary,
 * so it fails closed (excludes every lineage/deep/themes route) instead
 * of falling back to "the page got built, so list it".
 */
export function eligibleLineageRoutes(manifestRaw: string | null): Set<string> {
  const routes = new Set<string>();
  if (manifestRaw === null) return routes;
  let payload: unknown;
  try {
    payload = JSON.parse(manifestRaw);
  } catch {
    return routes;
  }
  if (typeof payload !== "object" || payload === null) return routes;
  const collections = (payload as { collections?: unknown }).collections;
  if (!Array.isArray(collections)) return routes;
  for (const row of collections as LineageQualityRow[]) {
    if (typeof row !== "object" || row === null) continue;
    if (row.availability !== "ready" || row.audit_status !== "passed") continue;
    if (row.kind === "conference" && typeof row.slug === "string") {
      routes.add(`/${row.slug}/lineage/`);
    } else if (row.kind === "theme") {
      routes.add("/themes/");
    } else if (row.kind === "deep" && typeof row.conference === "string") {
      routes.add(`/${row.conference}/deep/`);
    }
  }
  return routes;
}

const SLUG_RE = "[a-z0-9][a-z0-9-]*";
const LINEAGE_ROUTE_RE = new RegExp(`^/${SLUG_RE}/lineage/$`);
const DEEP_ROUTE_RE = new RegExp(`^/${SLUG_RE}/deep/$`);

/** Whether `path` is one this postbuild step must gate on the lineage
 * quality manifest before listing (CAT-39), independent of whether the
 * page itself happens to be noindex. */
export function isLineageGatedRoute(path: string): boolean {
  return path === "/themes/" || LINEAGE_ROUTE_RE.test(path) || DEEP_ROUTE_RE.test(path);
}

/** Characters that must not appear raw in XML text or attribute values. */
export function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Whether one built page belongs in the sitemap, by path only (the noindex
 * read is separate so callers can say *why* a page was dropped).
 *
 * `relPath` is out-relative and POSIX-style, e.g. "index.html",
 * "cvpr-2026/index.html". `404.html` is not an index file at all; Next also
 * writes internal routes under a `_`-prefixed segment (`_not-found/`), which
 * is not a public URL.
 */
export function isPublicIndexPage(relPath: string): boolean {
  if (!relPath.endsWith("index.html")) {
    return false;
  }
  return relPath.split("/").every((segment) => segment !== "404" && !segment.startsWith("_"));
}

/**
 * The site-relative URL a built index page is published at: the directory it
 * lives in, with a trailing slash (matching `trailingSlash: true`), and "/"
 * for the root `index.html`.
 */
export function sitePathFromIndexPage(relPath: string): string {
  const withoutFile = relPath.slice(0, -"index.html".length);
  return `/${withoutFile}`;
}

const META_TAG_RE = /<meta\b[^>]*>/gi;
const ROBOTS_NAME_RE = /\bname\s*=\s*(?:"robots"|'robots'|robots)/i;
const CONTENT_ATTR_RE = /\bcontent\s*=\s*(?:"([^"]*)"|'([^']*)')/i;

/** True when the page asks crawlers not to index it (Next emits this for
 * `robots: { index: false }`, e.g. the 404 page and generated duplicates). */
export function hasNoindexMeta(html: string): boolean {
  for (const match of html.match(META_TAG_RE) ?? []) {
    if (!ROBOTS_NAME_RE.test(match)) {
      continue;
    }
    const content = match.match(CONTENT_ATTR_RE);
    const value = content?.[1] ?? content?.[2] ?? "";
    if (/noindex/i.test(value)) {
      return true;
    }
  }
  return false;
}

/**
 * Absolute sitemap URLs: landing page first, then sorted by path.
 *
 * `eligibleLineageRoutesSet` defaults to empty -- the same fail-closed
 * default as `eligibleLineageRoutes(null)` -- so a caller that forgets
 * to pass it gets "exclude every lineage/deep/themes route" rather than
 * "list them unconditionally".
 */
export function sitemapUrls(
  pages: readonly BuiltPage[],
  eligibleLineageRoutesSet: ReadonlySet<string> = new Set(),
): string[] {
  const paths = pages
    .filter((page) => isPublicIndexPage(page.relPath) && !hasNoindexMeta(page.html))
    .map((page) => sitePathFromIndexPage(page.relPath))
    .filter((path) => !isLineageGatedRoute(path) || eligibleLineageRoutesSet.has(path));
  // All URLs share one origin, so a plain sort is also "landing first":
  // "/" is a prefix of every other path and therefore sorts before it.
  return [...new Set(paths)].sort().map((path) => canonicalUrl(path));
}

/** The sitemap document, in the same shape as docs/sitemap.xml. */
export function renderSitemap(urls: readonly string[]): string {
  const body = urls.map((url) => `  <url><loc>${escapeXml(url)}</loc></url>\n`).join("");
  return `${XML_DECLARATION}\n${HEADER_COMMENT}\n${URLSET_OPEN}\n${body}${URLSET_CLOSE}`;
}

/** Collects every `index.html` under `dir`, out-relative and POSIX-style. */
async function listIndexPages(dir: string, base: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const found: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...(await listIndexPages(full, base)));
    } else if (entry.isFile() && entry.name === "index.html") {
      found.push(
        full
          .slice(base.length + 1)
          .split(sep)
          .join("/"),
      );
    }
  }
  return found.sort();
}

async function collectPages(outDir: string): Promise<BuiltPage[]> {
  const relPaths = await listIndexPages(outDir, outDir);
  const pages: BuiltPage[] = [];
  for (const relPath of relPaths) {
    pages.push({ relPath, html: await readFile(join(outDir, relPath), "utf8") });
  }
  return pages;
}

/** Fails loudly instead of writing next to a missing build output. */
async function assertOutDir(outDir: string): Promise<void> {
  try {
    const info = await stat(outDir);
    if (!info.isDirectory()) {
      throw new Error("not a directory");
    }
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    throw new Error(`${outDir} is not a build output directory (${reason}); run next build first`);
  }
}

/** Reads the published `lineage-quality-v1.json` from `out/` (copied
 * there from `public/` by `next build`'s static export, itself copied
 * from `docs/` by the `prebuild` step) -- `null` on any read failure,
 * which `eligibleLineageRoutes` already treats as "exclude everything". */
async function readLineageQualityManifest(outDir: string): Promise<string | null> {
  try {
    return await readFile(join(outDir, "lineage-quality-v1.json"), "utf8");
  } catch {
    return null;
  }
}

async function main(): Promise<void> {
  await assertOutDir(OUT_DIR);
  const eligible = eligibleLineageRoutes(await readLineageQualityManifest(OUT_DIR));
  const urls = sitemapUrls(await collectPages(OUT_DIR), eligible);
  if (urls.length === 0) {
    throw new Error(`no public index.html pages under ${OUT_DIR}; run next build first`);
  }
  const target = join(OUT_DIR, "sitemap.xml");
  await writeFile(target, renderSitemap(urls), "utf8");
  console.log(`sitemap: wrote ${target} (${urls.length} URL(s))`);
}

/**
 * `main()` is skipped when this module is imported (a Vitest test drives the
 * pure functions above). See the identical note in scripts/redirects.ts.
 */
function invokedAsScript(): boolean {
  const entry = process.argv[1];
  return entry !== undefined && resolve(entry) === fileURLToPath(import.meta.url);
}

if (invokedAsScript()) {
  main().catch((err: unknown) => {
    console.error(err);
    process.exitCode = 1;
  });
}
