/**
 * Site-wide configuration constants.
 *
 * API_BASE is the origin of the CF Worker that serves /api/*. It must stay
 * in sync with the CSP connect-src directive generated by
 * scripts/csp-hash.ts.
 */
export const API_BASE = "https://paperpilot-themes.puuptdbkh082.workers.dev";
