/**
 * Typed fetch helpers for the themes area's published JSON (sibling of
 * lib/data.ts's helpers, kept in a separate file per the P2 brief so
 * page agents don't collide editing a shared file).
 *
 * Fetches, in order:
 *   - `/themes/themes-manifest.json` -- discovery only (SCR-31/32: a
 *     slug landing here means the pipeline wrote an artifact, NOT that
 *     it is eligible for display).
 *   - `/themes/_quality.json` -- optional badge telemetry, never a gate.
 *   - `/lineage-quality-v1.json` -- the shared fail-closed quality read
 *     model. Strict-parsed; any schema drift leaves every row
 *     ineligible (see lib/themes-quality.ts).
 *   - `/themes/<slug>/lineage.json` -- fetched ONLY through the quality
 *     gate (lib/themes-quality.ts's fetchJsonWithSha256 +
 *     qualityRowIsEligible/qualityRowIsPublishable), never from a raw
 *     slug.
 *
 * Every helper here degrades the same way the original docs/assets/
 * theme.js did (never throws; a failure collapses to "no data" for
 * telemetry-only fetches, or to `null`/error for gated ones) -- see
 * each function's docstring for its exact contract.
 */
import { BASE_PATH } from "@paperpilot/core/site";
import type { ThemeManifestEntry, ThemeQualityRollup } from "./themes-gallery";
import type { LineageArtifact, QualityManifest, QualityRow } from "./themes-quality";
import {
  fetchJsonWithSha256,
  parseArtifact,
  parseQualityManifest,
  qualityRowIsEligible,
  qualityRowIsPublishable,
  resolveQualityCollection,
} from "./themes-quality";
import type { GithubActionsRun, QualityPollOutcome } from "./themes-request";
import { statusUrlForRequest } from "./themes-request";
import { SLUG_RE } from "./themes-slug";

export type DataResult<T> = { status: "ok"; data: T } | { status: "error"; error: string };

function publicPath(path: string): string {
  if (!path.startsWith("/")) {
    throw new Error(`publicPath: path must start with "/", got ${JSON.stringify(path)}`);
  }
  return `${BASE_PATH}${path}`;
}

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

/** Fetches `/themes/themes-manifest.json`. Filters to entries with a
 * syntactically valid slug (anything else can never be safely spliced
 * into a fetch URL) -- this is discovery only, NOT the publication
 * gate; see `eligibleThemeManifest` in lib/themes-gallery.ts for that. */
export async function fetchThemesManifest({
  cache = "no-cache",
}: {
  cache?: RequestCache;
} = {}): Promise<DataResult<ThemeManifestEntry[]>> {
  try {
    const res = await fetch(publicPath("/themes/themes-manifest.json"), { cache });
    if (!res.ok) {
      return { status: "error", error: `themes-manifest.json: HTTP ${res.status}` };
    }
    const raw: unknown = await res.json();
    if (!Array.isArray(raw)) {
      return { status: "error", error: "themes-manifest.json: expected an array" };
    }
    const entries = raw.filter(
      (e): e is ThemeManifestEntry =>
        !!e &&
        typeof e === "object" &&
        typeof (e as { slug?: unknown }).slug === "string" &&
        SLUG_RE.test((e as { slug: string }).slug),
    );
    return { status: "ok", data: entries };
  } catch (err) {
    return { status: "error", error: errorMessage(err) };
  }
}

/**
 * Fetches `/themes/_quality.json` (generated by
 * `paperpilot.scripts.compute_theme_quality` alongside the manifest).
 * Optional telemetry: any failure or schema mismatch returns `{}` so
 * an older snapshot without the file (or a transient fetch error)
 * still renders the gallery, just without badges.
 */
export async function fetchThemeQualityRollup(): Promise<ThemeQualityRollup> {
  try {
    const res = await fetch(publicPath("/themes/_quality.json"), { cache: "no-cache" });
    if (!res.ok) return {};
    const data: unknown = await res.json();
    const themes = (data as { themes?: unknown } | null)?.themes;
    return themes && typeof themes === "object" && !Array.isArray(themes)
      ? (themes as ThemeQualityRollup)
      : {};
  } catch {
    return {};
  }
}

/**
 * Fetches the shared fail-closed quality read model
 * (`/lineage-quality-v1.json`). Strict parse via
 * `parseQualityManifest`: any schema drift returns `null`, leaving
 * every row ineligible -- never a partial/best-effort read.
 */
export async function fetchLineageQualityManifest(): Promise<QualityManifest | null> {
  const loaded = await fetchJsonWithSha256(publicPath("/lineage-quality-v1.json"), {
    cache: "no-cache",
  });
  return loaded ? parseQualityManifest(loaded.data) : null;
}

/**
 * P2T quality gate (SCR-31/32): fetches and returns the parsed theme
 * artifact ONLY when `slug`'s quality row is ready+passed, the fetched
 * bytes hash to the audited `input_sha256`, and the payload strict-
 * parses as `lineage-artifact-v1` with `kind: "theme"`. The fetch URL
 * is assembled from the validated row's `path` -- the raw `slug`
 * parameter is never spliced into a URL. Returns `null` on any gate
 * failure (missing row, hash mismatch, malformed payload) -- all
 * collapse to "do not render", never a partial artifact.
 */
export async function fetchThemeArtifact(
  slug: string,
  quality: QualityManifest | null,
): Promise<LineageArtifact | null> {
  const row: QualityRow | null = resolveQualityCollection(quality, { kind: "theme", slug });
  if (!row || !qualityRowIsEligible(row)) return null;
  const loaded = await fetchJsonWithSha256(
    publicPath(`/${row.path}`),
    { cache: "no-cache" },
    { expectedSha256: row.input_sha256 },
  );
  if (!loaded || !qualityRowIsPublishable(row, { artifactSha256: loaded.sha256 })) return null;
  return parseArtifact(loaded.data, { kind: "theme" });
}

/**
 * Re-checks the shared quality file + eligibility rule for `slug`
 * (issue M-4, SCR-39): landing in `themes-manifest.json` only means the
 * pipeline wrote an artifact, not that its quality audit passed. Used
 * by the generation-progress poll loop so it never redirects into a
 * page that will immediately render nothing for an audit-failed theme.
 */
export async function pollThemeQualityOutcome(slug: string): Promise<QualityPollOutcome> {
  const quality = await fetchLineageQualityManifest();
  if (!quality) return "pending";
  const row = resolveQualityCollection(quality, { kind: "theme", slug });
  if (!row) return "pending";
  return qualityRowIsEligible(row) ? "ready" : "failed";
}

/**
 * Best-effort fetch of the Worker's GitHub Actions run summary for
 * `requestId` (API-19: the status endpoint is dormant in production --
 * always a cacheable-miss 503 -- so this routinely resolves to `null`;
 * the manifest/quality poll loop is the actual completion signal). A
 * network error, non-OK response, or malformed body all collapse to
 * `null`, never a thrown exception.
 */
export async function fetchThemeRunStatus(
  apiBase: string | null | undefined,
  requestId: string,
): Promise<GithubActionsRun | null> {
  const url = statusUrlForRequest(apiBase, requestId);
  if (!url) return null;
  try {
    const res = await fetch(url, { credentials: "omit" });
    if (!res.ok) return null;
    const data: unknown = await res.json();
    const run = (data as { run?: unknown } | null)?.run;
    return run && typeof run === "object" ? (run as GithubActionsRun) : null;
  } catch {
    return null;
  }
}
