/**
 * pyStrip / pyLstrip / pyRstrip / pySplit — reproduce Python 3's `str.strip()`
 * / `str.lstrip()` / `str.rstrip()` / `str.split()` (all four with **no**
 * argument — the whitespace-driven form; none of these port the
 * separator/`chars` overloads).
 *
 * ## The whitespace set differs from JS's `\s` / `.trim()`
 *
 * `String.prototype.trim()` and the ECMAScript `\s` regex class strip/match
 * `WhiteSpace` + `LineTerminator` code points (tab, LF, VT, FF, CR, space,
 * NBSP U+00A0, BOM/ZWNBSP U+FEFF, the Unicode `Zs` category, and
 * U+2028/U+2029). Python's `str.isspace()` — which is what `str.strip()` and
 * the no-arg `str.split()` both key off — uses a **different** set: every
 * `Zs` category code point plus specifically the characters whose Unicode
 * *bidirectional class* is `WS`, `B`, or `S`. The two sets mostly overlap but
 * disagree on two groups that matter here:
 *
 * - **Python-only whitespace**: U+001C–U+001F (the C0 "separator" controls:
 *   FILE/GROUP/RECORD/UNIT SEPARATOR) and U+0085 (NEL, NEXT LINE). JS's
 *   `\s`/`.trim()` do NOT treat these as whitespace, so a `.trim()`/`split(/\s+/)`
 *   port silently leaves these characters in place (or mid-string, fails to
 *   split on them) where Python would strip/split on them.
 * - **JS-only whitespace**: U+FEFF (BYTE ORDER MARK / ZERO WIDTH NO-BREAK
 *   SPACE). `.trim()` strips it; Python's `str.strip()` does NOT (`"﻿x".isspace()`
 *   is `False` for that character, and `"﻿x".strip() == "﻿x"`
 *   unchanged). A naive `.trim()` port would therefore strip a BOM Python
 *   leaves behind.
 *
 * The exact 29-code-point set below was generated by actually asking CPython
 * (`[cp for cp in range(0x110000) if chr(cp).isspace()]`) rather than
 * hand-transcribed from the Unicode tables, to avoid exactly this kind of
 * off-by-a-few-code-points mistake. All 29 are in the Basic Multilingual
 * Plane (max U+3000), so plain UTF-16 code-unit indexing (no surrogate-pair
 * handling) is sufficient — no code point used here is ever split across two
 * UTF-16 code units.
 *
 * ## pySplit
 *
 * Python's `s.split()` (no separator) splits on *runs* of the whitespace
 * set above, discards leading/trailing whitespace, and never produces empty
 * strings — `"".split() == []` and `"   ".split() == []`, not `[""]`. This
 * is NOT the same as `s.split(/\s+/)` in JS, which (for a string with
 * leading/trailing whitespace) produces leading/trailing `""` entries that
 * then have to be filtered out by hand — easy to forget, and still subject
 * to the whitespace-set gap above even when remembered.
 *
 * Verified against real CPython output; see
 * packages/core/test/pycompat/whitespace.test.ts and
 * packages/core/test/pycompat/fixtures/gen.py (`gen_strip_split_cases`).
 */

/** The exact 29 code points for which CPython's `str.isspace()` is `True`. */
const PY_WHITESPACE_CODEPOINTS: ReadonlySet<number> = new Set([
  0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x85, 0xa0, 0x1680, 0x2000, 0x2001,
  0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200a, 0x2028, 0x2029, 0x202f,
  0x205f, 0x3000,
]);

function isPyWhitespaceCodeUnit(code: number): boolean {
  return PY_WHITESPACE_CODEPOINTS.has(code);
}

export function pyLstrip(s: string): string {
  let start = 0;
  while (start < s.length && isPyWhitespaceCodeUnit(s.charCodeAt(start))) start += 1;
  return s.slice(start);
}

export function pyRstrip(s: string): string {
  let end = s.length;
  while (end > 0 && isPyWhitespaceCodeUnit(s.charCodeAt(end - 1))) end -= 1;
  return s.slice(0, end);
}

export function pyStrip(s: string): string {
  let start = 0;
  let end = s.length;
  while (start < end && isPyWhitespaceCodeUnit(s.charCodeAt(start))) start += 1;
  while (end > start && isPyWhitespaceCodeUnit(s.charCodeAt(end - 1))) end -= 1;
  return s.slice(start, end);
}

/** `str.split()` with no separator: split on whitespace runs, no empty tokens. */
export function pySplit(s: string): string[] {
  const out: string[] = [];
  const n = s.length;
  let i = 0;
  while (i < n) {
    while (i < n && isPyWhitespaceCodeUnit(s.charCodeAt(i))) i += 1;
    if (i >= n) break;
    const start = i;
    while (i < n && !isPyWhitespaceCodeUnit(s.charCodeAt(i))) i += 1;
    out.push(s.slice(start, i));
  }
  return out;
}
