/**
 * Agreement test: for every (published file, schema) pair discovered
 * during the P1 schema inventory (docs/migration/schema-inventory.md),
 * the ajv (draft 2020-12) verdict here must equal the Python
 * `jsonschema.Draft202012Validator` verdict recorded once in
 * `fixtures/python-verdicts.json` (generated by
 * `fixtures/generate-python-verdicts.py`, see that file's docstring for
 * how to regenerate it).
 *
 * This is deliberately a comparison against a frozen fixture, not a live
 * Python subprocess per test run: packages/core must not depend on `uv`/
 * Python being on PATH to run `vitest run` (see design doc §3's "一致す
 * るテスト" requirement, and the task's hard limit of no new tool
 * invocations beyond the allowed pnpm/vitest/tsc commands).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { auditFixtures, identityCoverage, layoutFor, relLayout } from "../../src/layout/index.js";
import { getRepoRoot, listSchemaNames, validateArtifact } from "../../src/schemas/index.js";

/**
 * `python-verdicts.json`'s `file` fields were recorded once (frozen
 * fixture, see this file's header doc comment) against the legacy roots,
 * since that is what existed when the fixture was generated: 385 cases
 * under `docs/` (-> `layout.published`), plus two individually-named
 * files under `paperpilot/data/` whose p5 destination differs
 * (`identity-coverage-v1.json` -> `layout.state`;
 * `lineage-audit-fixtures-v1.json` -> `layout.config` -- the two roots
 * that both happen to equal `paperpilot/data` under legacy but diverge
 * under p5). Resolving every one of these against the CURRENT
 * `LAYOUT_MODE` (via the layout module's own named helpers, never a
 * hard-coded `"docs"`/`"paperpilot/data"`) is what lets this suite stay
 * green after the A9 data-move commit relocates them -- the fixture's
 * *filenames* don't change, only where they live on disk.
 */
function resolvePublishedFixturePath(repoRoot: string, legacyRelPath: string): string {
  const layout = layoutFor(repoRoot);
  const docsPrefix = `${relLayout("legacy").published}/`;
  if (legacyRelPath.startsWith(docsPrefix)) {
    return join(layout.published, legacyRelPath.slice(docsPrefix.length));
  }
  if (legacyRelPath === "paperpilot/data/identity-coverage-v1.json") {
    return identityCoverage(layout);
  }
  if (legacyRelPath === "paperpilot/data/lineage-audit-fixtures-v1.json") {
    return auditFixtures(layout);
  }
  throw new Error(
    `python-verdicts.json fixture path ${JSON.stringify(legacyRelPath)} has no known ` +
      "layout mapping (resolvePublishedFixturePath needs a new case)",
  );
}

interface SampleError {
  path: string;
  message: string;
}

interface PythonVerdictCase {
  file: string;
  schema: string;
  ok: boolean;
  errorCount: number;
  sampleErrors: SampleError[];
}

interface PythonVerdictFixture {
  generatedAt: string;
  generator: string;
  validator: string;
  caseCount: number;
  cases: PythonVerdictCase[];
  excluded: Array<PythonVerdictCase & { reason: string }>;
}

const fixturePath = join(
  fileURLToPath(new URL(".", import.meta.url)),
  "fixtures",
  "python-verdicts.json",
);
const fixture: PythonVerdictFixture = JSON.parse(readFileSync(fixturePath, "utf8"));

describe("python-verdicts.json fixture", () => {
  it("has at least one case and matches its own caseCount", () => {
    expect(fixture.cases.length).toBeGreaterThan(0);
    expect(fixture.cases.length).toBe(fixture.caseCount);
  });

  it("documents the YAML exclusion instead of silently dropping it", () => {
    // conference-sources-v1's only published artifact is YAML
    // (paperpilot/data/conference-sources-v1.yaml); packages/core has no
    // YAML parser dependency under this task's hard limits, so it cannot
    // be exercised through ajv. It must still show up here, with a
    // reason, rather than vanishing from the record (see
    // docs/migration/schema-inventory.md §5).
    expect(fixture.excluded.length).toBeGreaterThan(0);
    const yamlCase = fixture.excluded.find((c) => c.file.endsWith(".yaml"));
    expect(yamlCase).toBeDefined();
    expect(yamlCase?.reason).toMatch(/YAML/);
  });
});

describe("ajv vs Python jsonschema agreement", () => {
  for (const testCase of fixture.cases) {
    // identity-aliases-v1 is a flat `uniqueItems: true` array of 28,300
    // non-scalar 3-tuples. ajv's uniqueItems check falls back to pairwise
    // deep-equal for non-scalar items (no fast hash path), which is
    // algorithmically O(n^2) here and takes several seconds -- a real
    // cost of this schema/data shape, not a bug, so it gets a longer
    // per-test timeout instead of a smaller/sampled fixture.
    const timeout = testCase.file.includes("identity-aliases-v1") ? 30_000 : 5_000;
    it(
      `${testCase.file} against ${testCase.schema} (python ok=${testCase.ok})`,
      () => {
        const absolutePath = resolvePublishedFixturePath(getRepoRoot(), testCase.file);
        const data = JSON.parse(readFileSync(absolutePath, "utf8"));
        const result = validateArtifact(testCase.schema, data);

        if (result.ok !== testCase.ok) {
          const ajvDetail = result.errors
            ?.slice(0, 5)
            .map((e) => `${e.instancePath || "/"} ${e.message ?? ""}`)
            .join("; ");
          const pyDetail = testCase.sampleErrors.map((e) => `${e.path} ${e.message}`).join("; ");
          throw new Error(
            `disagreement for ${testCase.file} vs ${testCase.schema}: ` +
              `ajv ok=${result.ok} (${ajvDetail ?? "no errors"}) vs python ok=${testCase.ok} (${pyDetail || "no errors"})`,
          );
        }
        expect(result.ok).toBe(testCase.ok);
      },
      timeout,
    );
  }
});

describe("validateArtifact basics", () => {
  it("exposes all 23 repo schemas by name", () => {
    const names = listSchemaNames();
    expect(names.length).toBe(23);
    expect(names).toContain("lineage-artifact-v1");
    expect(names).toContain("search-index-v2");
  });

  it("resolves the single cross-file $ref (conference-release-state-v1 -> conference-probe-observation-v1)", () => {
    // A minimal payload that is valid *only* if the referenced
    // conference-probe-observation-v1 subschema was actually resolved
    // (an unresolved $ref would make ajv throw at compile/use time
    // instead of returning a normal ok:false).
    const result = validateArtifact("conference-release-state-v1", {});
    expect(result.errors).not.toBeNull();
  });

  it("throws a clear error for an unknown schema name", () => {
    expect(() => validateArtifact("not-a-real-schema", {})).toThrow(/unknown schema name/);
  });

  it("accepts the name with or without the .schema.json suffix", () => {
    const a = validateArtifact("search-index-v2", []);
    const b = validateArtifact("search-index-v2.schema.json", []);
    expect(a.ok).toBe(b.ok);
  });
});

// Design doc 41 D1/D5 additions (no frozen Python verdict exists for them:
// Python is gone, so they are pinned here against ajv directly).
describe("lineage publication tiers and edge labels (design doc 41)", () => {
  const SHA = "a".repeat(64);
  function check(name: string, status: string) {
    return { name, status, observed: 0, expected: 0, evidence: [] };
  }
  function qualityRow(overrides: Record<string, unknown>) {
    return {
      collection_id: "theme:t",
      kind: "theme",
      slug: "t",
      label: "T",
      path: "themes/t/lineage.json",
      availability: "ready",
      audit_status: "unknown",
      publication_tier: "unaudited",
      freshness: "fresh",
      generated_at: null,
      snapshot_date: null,
      node_count: 2,
      edge_count: 1,
      artifact_schema_version: "lineage-artifact-v1",
      input_sha256: SHA,
      audit: {
        fixture_sha256: null,
        evaluated_at: "2026-10-10T00:00:00Z",
        actor: "ci:audit-v1",
        checks: [check("artifact_contract_v1", "passed"), check("golden_fixture", "unknown")],
      },
      ...overrides,
    };
  }
  function quality(row: Record<string, unknown>) {
    return {
      schema_version: "lineage-quality-v1",
      as_of: "2026-10-10T00:00:00Z",
      audit_version: "audit-v1",
      collections: [row],
    };
  }

  it("accepts an unaudited row and rejects one whose automatic checks did not all pass", () => {
    expect(validateArtifact("lineage-quality-v1", quality(qualityRow({}))).ok).toBe(true);
    const failing = qualityRow({
      audit: {
        fixture_sha256: null,
        evaluated_at: "2026-10-10T00:00:00Z",
        actor: "ci:audit-v1",
        checks: [check("artifact_contract_v1", "unknown"), check("golden_fixture", "unknown")],
      },
    });
    expect(validateArtifact("lineage-quality-v1", quality(failing)).ok).toBe(false);
  });

  it("rejects 'audited' unless the row is ready+passed, and ready+passed unless 'audited'", () => {
    expect(
      validateArtifact("lineage-quality-v1", quality(qualityRow({ publication_tier: "audited" })))
        .ok,
    ).toBe(false);
    const passed = qualityRow({
      audit_status: "passed",
      publication_tier: "unaudited",
      audit: {
        fixture_sha256: SHA,
        evaluated_at: "2026-10-10T00:00:00Z",
        actor: "ci:audit-v1",
        checks: [check("artifact_contract_v1", "passed"), check("golden_fixture", "passed")],
      },
    });
    expect(validateArtifact("lineage-quality-v1", quality(passed)).ok).toBe(false);
    expect(
      validateArtifact("lineage-quality-v1", quality({ ...passed, publication_tier: "audited" }))
        .ok,
    ).toBe(true);
  });

  it("accepts edge_labels in audit fixtures and forbids corrected_relation on a 'correct' verdict", () => {
    const fixture = (edgeLabel: Record<string, unknown>) => ({
      schema_version: "lineage-audit-fixtures-v1",
      collections: [
        {
          collection_id: "theme:t",
          input_sha256: SHA,
          reviewer: "r",
          reviewed_at: "2026-10-10T00:00:00Z",
          focus_labels: [],
          sample_labels: [],
          edge_labels: [edgeLabel],
        },
      ],
    });
    const base = { src: "a", dst: "b", relation: "contrasts", verdict: "correct" };
    expect(validateArtifact("lineage-audit-fixtures-v1", fixture(base)).ok).toBe(true);
    expect(
      validateArtifact(
        "lineage-audit-fixtures-v1",
        fixture({ ...base, verdict: "wrong", corrected_relation: "extends", note: "n" }),
      ).ok,
    ).toBe(true);
    expect(
      validateArtifact("lineage-audit-fixtures-v1", fixture({ ...base, corrected_relation: "x" }))
        .ok,
    ).toBe(false);
    expect(
      validateArtifact("lineage-audit-fixtures-v1", fixture({ ...base, verdict: "maybe" })).ok,
    ).toBe(false);
  });

  it("accepts metadata_ok/note on node labels and draft_sha256 on entries (design doc 41 D5)", () => {
    const fixture = (label: Record<string, unknown>) => ({
      schema_version: "lineage-audit-fixtures-v1",
      collections: [
        {
          collection_id: "theme:t",
          input_sha256: SHA,
          draft_sha256: SHA,
          reviewer: "r",
          reviewed_at: "2026-10-10T00:00:00Z",
          focus_labels: [label],
          sample_labels: [label],
        },
      ],
    });
    const base = { node_id: "a", on_topic: true };
    expect(
      validateArtifact(
        "lineage-audit-fixtures-v1",
        fixture({ ...base, metadata_ok: false, note: "n" }),
      ).ok,
    ).toBe(true);
    expect(
      validateArtifact("lineage-audit-fixtures-v1", fixture({ ...base, metadata_ok: "yes" })).ok,
    ).toBe(false);
    expect(validateArtifact("lineage-audit-fixtures-v1", fixture({ ...base, extra: 1 })).ok).toBe(
      false,
    );
  });
});

// R2-10 (design 41 D6): the Semantic Scholar context-rule classification
// method. Pinned against ajv directly (no frozen Python verdict exists).
describe("lineage-artifact-v1 classification methods (design 41 D6)", () => {
  function themeArtifact(method: string) {
    const repoRoot = getRepoRoot();
    const doc = JSON.parse(
      readFileSync(
        join(layoutFor(repoRoot).published, "themes", "graph-neural-network", "lineage.json"),
        "utf-8",
      ),
    );
    const edge = doc.edges[0];
    edge.provenance.classification = {
      method,
      provider: null,
      model: null,
      prompt_version: null,
      schema_version: "relation-classification-v1",
    };
    return doc;
  }

  it("accepts s2_context_rule and still rejects an unknown method", () => {
    expect(validateArtifact("lineage-artifact-v1", themeArtifact("citation_heuristic")).ok).toBe(
      true,
    );
    expect(validateArtifact("lineage-artifact-v1", themeArtifact("s2_context_rule")).ok).toBe(true);
    expect(validateArtifact("lineage-artifact-v1", themeArtifact("s2_magic")).ok).toBe(false);
  });
});
