/**
 * Agreement test: for every (published file, schema) pair discovered
 * during the P1 schema inventory (docs/migration/schema-inventory.md),
 * the ajv (draft 2020-12) verdict here must equal the Python
 * `jsonschema.Draft202012Validator` verdict recorded once in
 * `fixtures/python-verdicts.json` (generated by
 * `fixtures/generate-python-verdicts.py`, see that file's docstring for
 * how to regenerate it).
 *
 * This is deliberately a comparison against a frozen fixture, not a live
 * Python subprocess per test run: packages/core must not depend on `uv`/
 * Python being on PATH to run `vitest run` (see design doc §3's "一致す
 * るテスト" requirement, and the task's hard limit of no new tool
 * invocations beyond the allowed pnpm/vitest/tsc commands).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { getRepoRoot, listSchemaNames, validateArtifact } from "../../src/schemas/index.js";

interface SampleError {
  path: string;
  message: string;
}

interface PythonVerdictCase {
  file: string;
  schema: string;
  ok: boolean;
  errorCount: number;
  sampleErrors: SampleError[];
}

interface PythonVerdictFixture {
  generatedAt: string;
  generator: string;
  validator: string;
  caseCount: number;
  cases: PythonVerdictCase[];
  excluded: Array<PythonVerdictCase & { reason: string }>;
}

const fixturePath = join(
  fileURLToPath(new URL(".", import.meta.url)),
  "fixtures",
  "python-verdicts.json",
);
const fixture: PythonVerdictFixture = JSON.parse(readFileSync(fixturePath, "utf8"));

describe("python-verdicts.json fixture", () => {
  it("has at least one case and matches its own caseCount", () => {
    expect(fixture.cases.length).toBeGreaterThan(0);
    expect(fixture.cases.length).toBe(fixture.caseCount);
  });

  it("documents the YAML exclusion instead of silently dropping it", () => {
    // conference-sources-v1's only published artifact is YAML
    // (paperpilot/data/conference-sources-v1.yaml); packages/core has no
    // YAML parser dependency under this task's hard limits, so it cannot
    // be exercised through ajv. It must still show up here, with a
    // reason, rather than vanishing from the record (see
    // docs/migration/schema-inventory.md §5).
    expect(fixture.excluded.length).toBeGreaterThan(0);
    const yamlCase = fixture.excluded.find((c) => c.file.endsWith(".yaml"));
    expect(yamlCase).toBeDefined();
    expect(yamlCase?.reason).toMatch(/YAML/);
  });
});

describe("ajv vs Python jsonschema agreement", () => {
  for (const testCase of fixture.cases) {
    // identity-aliases-v1 is a flat `uniqueItems: true` array of 28,300
    // non-scalar 3-tuples. ajv's uniqueItems check falls back to pairwise
    // deep-equal for non-scalar items (no fast hash path), which is
    // algorithmically O(n^2) here and takes several seconds -- a real
    // cost of this schema/data shape, not a bug, so it gets a longer
    // per-test timeout instead of a smaller/sampled fixture.
    const timeout = testCase.file.includes("identity-aliases-v1") ? 30_000 : 5_000;
    it(
      `${testCase.file} against ${testCase.schema} (python ok=${testCase.ok})`,
      () => {
        const absolutePath = join(getRepoRoot(), testCase.file);
        const data = JSON.parse(readFileSync(absolutePath, "utf8"));
        const result = validateArtifact(testCase.schema, data);

        if (result.ok !== testCase.ok) {
          const ajvDetail = result.errors
            ?.slice(0, 5)
            .map((e) => `${e.instancePath || "/"} ${e.message ?? ""}`)
            .join("; ");
          const pyDetail = testCase.sampleErrors.map((e) => `${e.path} ${e.message}`).join("; ");
          throw new Error(
            `disagreement for ${testCase.file} vs ${testCase.schema}: ` +
              `ajv ok=${result.ok} (${ajvDetail ?? "no errors"}) vs python ok=${testCase.ok} (${pyDetail || "no errors"})`,
          );
        }
        expect(result.ok).toBe(testCase.ok);
      },
      timeout,
    );
  }
});

describe("validateArtifact basics", () => {
  it("exposes all 23 repo schemas by name", () => {
    const names = listSchemaNames();
    expect(names.length).toBe(23);
    expect(names).toContain("lineage-artifact-v1");
    expect(names).toContain("search-index-v2");
  });

  it("resolves the single cross-file $ref (conference-release-state-v1 -> conference-probe-observation-v1)", () => {
    // A minimal payload that is valid *only* if the referenced
    // conference-probe-observation-v1 subschema was actually resolved
    // (an unresolved $ref would make ajv throw at compile/use time
    // instead of returning a normal ok:false).
    const result = validateArtifact("conference-release-state-v1", {});
    expect(result.errors).not.toBeNull();
  });

  it("throws a clear error for an unknown schema name", () => {
    expect(() => validateArtifact("not-a-real-schema", {})).toThrow(/unknown schema name/);
  });

  it("accepts the name with or without the .schema.json suffix", () => {
    const a = validateArtifact("search-index-v2", []);
    const b = validateArtifact("search-index-v2.schema.json", []);
    expect(a.ok).toBe(b.ok);
  });
});
