/**
 * Byte-for-byte parity between `collect_openreview.py` (committed Python
 * fixture, generated by `run_python.py` — never re-run here) and
 * `runOpenreviewMain` for the SAME canned OpenReview API response, under a
 * fixed clock (design doc §7.2).
 *
 * Regenerate the Python side after a behavior change with:
 *   uv run --extra dev python apps/pipeline/test/conference/fixtures/openreview/run_python.py happy apps/pipeline/test/conference/fixtures/openreview/expected/happy
 *   uv run --extra dev python apps/pipeline/test/conference/fixtures/openreview/run_python.py incomplete apps/pipeline/test/conference/fixtures/openreview/expected/incomplete
 */
import { existsSync, mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { runOpenreviewMain } from "../../../../src/conference/openreview/main.js";
import { compareTrees } from "../../../../src/parity/compare-trees.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const NOTES: unknown[] = JSON.parse(readFileSync(join(HERE, "notes.json"), "utf-8"));

function pageOf(notes: unknown[]) {
  return { status: 200, json: async () => ({ notes }) };
}

describe("openreview parity: happy path", () => {
  it("TS output matches the committed Python fixture byte-for-byte", async () => {
    const actualOutDir = mkdtempSync(join(tmpdir(), "openreview-parity-happy-"));
    const fetchImpl = async (url: string) => {
      const offset = Number(new URL(url).searchParams.get("offset"));
      return pageOf(offset === 0 ? NOTES : []);
    };

    const rc = await runOpenreviewMain(
      ["--conference", "iclr-2025", "--venue", "ICLR", "--venueid", "ICLR.cc/2025/Conference"],
      {
        outputRoot: join(actualOutDir, "output"),
        request: { fetchImpl },
        now: () => new Date(Date.UTC(2026, 5, 28)), // 2026-06-28 (month is 0-indexed)
        print: () => {},
      },
    );
    expect(rc).toBe(0);

    const report = await compareTrees({
      expectedRoot: join(HERE, "expected", "happy", "output"),
      actualRoot: join(actualOutDir, "output"),
    });
    expect(report.equal, JSON.stringify(report, null, 2)).toBe(true);
  });
});

describe("openreview parity: incomplete pagination (CNF-01) failure path", () => {
  it("TS exits 1 and writes nothing, matching the Python side's exit code", async () => {
    const actualOutDir = mkdtempSync(join(tmpdir(), "openreview-parity-incomplete-"));
    const page1 = Array.from({ length: 1000 }, (_, i) => ({
      id: `note-${i}`,
      content: {
        title: { value: `Paper ${i}` },
        venue: { value: "ICLR 2025 Poster" },
        venueid: { value: "ICLR.cc/2025/Conference" },
      },
    }));
    const fetchImpl = async (url: string) => {
      const offset = Number(new URL(url).searchParams.get("offset"));
      if (offset === 0) return pageOf(page1);
      return { status: 500, json: async () => ({}) };
    };

    const rc = await runOpenreviewMain(
      ["--conference", "iclr-2025", "--venue", "ICLR", "--venueid", "ICLR.cc/2025/Conference"],
      {
        outputRoot: join(actualOutDir, "output"),
        request: { fetchImpl, sleep: async () => {} },
        now: () => new Date(Date.UTC(2026, 5, 28)),
        print: () => {},
      },
    );

    const expectedManifest = JSON.parse(
      readFileSync(join(HERE, "expected", "incomplete", "manifest.json"), "utf-8"),
    );
    expect(rc).toBe(expectedManifest.exitCode);
    expect(existsSync(join(actualOutDir, "output"))).toBe(false);
  });
});
