/**
 * `marker` byte-identity tests (p5-plan.md §2 A4). The two fixtures under
 * `fixtures/` were generated by running the EXACT Python snippet from
 * `.github/workflows/pages-release.yml`'s "Write deterministic deployment
 * marker" step once, offline, with `python3`:
 *
 *   SOURCE_SHA=<40 a's> RELEASE_KIND=normal REQUEST_ID=push-123-1
 *   SOURCE_SHA=<40 b's> RELEASE_KIND=rollback REQUEST_ID=""
 *
 * and comparing this module's output to those bytes with `Buffer.equals`,
 * not string/value equality, so key order, separators, and the trailing
 * newline are all pinned.
 */
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, expect, it } from "vitest";
import {
  buildMarkerJson,
  MarkerError,
  readMarkerJson,
  writeMarker,
} from "../../src/release/marker.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(__dirname, "fixtures");

const SHA_A = "a".repeat(40);
const SHA_B = "b".repeat(40);

it("buildMarkerJson is byte-identical to the Python one-liner's output (with a request id)", () => {
  const actual = Buffer.from(
    buildMarkerJson({ sourceSha: SHA_A, releaseKind: "normal", requestId: "push-123-1" }),
  );
  const expected = readFileSync(join(FIXTURES, "marker-with-request-id.json"));
  expect(actual.equals(expected)).toBe(true);
});

it("buildMarkerJson is byte-identical to the Python one-liner's output (empty request id -> null)", () => {
  const actual = Buffer.from(
    buildMarkerJson({ sourceSha: SHA_B, releaseKind: "rollback", requestId: "" }),
  );
  const expected = readFileSync(join(FIXTURES, "marker-null-request-id.json"));
  expect(actual.equals(expected)).toBe(true);
});

it("rejects a malformed SOURCE_SHA", () => {
  expect(() =>
    buildMarkerJson({ sourceSha: "not-a-sha", releaseKind: "normal", requestId: "" }),
  ).toThrow(MarkerError);
});

it("rejects a RELEASE_KIND other than normal/rollback", () => {
  expect(() => buildMarkerJson({ sourceSha: SHA_A, releaseKind: "bogus", requestId: "" })).toThrow(
    /RELEASE_KIND/,
  );
});

it("rejects a REQUEST_ID with an invalid format", () => {
  expect(() =>
    buildMarkerJson({ sourceSha: SHA_A, releaseKind: "normal", requestId: "has a space" }),
  ).toThrow(/REQUEST_ID/);
});

// Newline-injection shaped input: a REQUEST_ID crafted to break out of the
// JSON string must still fail the format check (the regex has no `\n`/`"`
// in its allowed character class), not get encoded into the marker.
it("rejects a REQUEST_ID containing a newline or quote", () => {
  expect(() =>
    buildMarkerJson({ sourceSha: SHA_A, releaseKind: "normal", requestId: 'x"\n' }),
  ).toThrow(MarkerError);
});

let outDir: string;
beforeEach(() => {
  outDir = mkdtempSync(join(tmpdir(), "paperpilot-marker-"));
});
afterEach(() => {
  rmSync(outDir, { recursive: true, force: true });
});

it("writeMarker writes the file under out-dir and readMarkerJson reads it back", () => {
  const path = writeMarker({ outDir, sourceSha: SHA_A, releaseKind: "normal", requestId: "" });
  expect(path).toBe(join(outDir, "_paperpilot-deployment.json"));
  const text = readMarkerJson(outDir);
  expect(JSON.parse(text)).toEqual({
    release_kind: "normal",
    request_id: null,
    schema_version: "paperpilot-deployment-v1",
    source_sha: SHA_A,
  });
});

it("writeMarker rejects a nonexistent out-dir", () => {
  expect(() =>
    writeMarker({
      outDir: join(outDir, "nope"),
      sourceSha: SHA_A,
      releaseKind: "normal",
      requestId: "",
    }),
  ).toThrow(/out-dir does not exist/);
});

it("writeMarker rejects an out-dir that is a file, not a directory", () => {
  mkdirSync(join(outDir, "sub"));
  const filePath = join(outDir, "sub", "a-file");
  writeFileSync(filePath, "x");
  expect(() =>
    writeMarker({ outDir: filePath, sourceSha: SHA_A, releaseKind: "normal", requestId: "" }),
  ).toThrow(/out-dir does not exist/);
});
