/**
 * Parity harness (design doc §7.2) for `buildDeep` (TS port of
 * `build_deep_lineage.py::build_deep`).
 *
 * The fixture was generated by running the real Python `build_deep` under
 * `uv run --extra dev python apps/pipeline/test/lineage/deep/fixtures/
 * dump_python_build_deep_lineage.py` against a canned S2 response map and a
 * fake LLM provider whose `complete_json` returns an EMPTY rationale for
 * one edge — exercising `_slot_fill_rationale`'s fallback (LIN-36), which is
 * this module's whole reason for having its own lenient classifier instead
 * of reusing `buildLineage.ts`'s strict one. No network; committed so this
 * test does not depend on Python being installed to run. `meta.generated_at`
 * is excluded from the comparison (the Python fixture pins it to the
 * literal string `"FIXED"` since `build_deep`'s `generated_at` field is
 * computed from `time.gmtime()` directly, not through an injectable clock).
 */
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import type {
  LLMProvider,
  PaperEvaluation,
  RelationClassification,
} from "../../../src/collect/llm/provider.js";
import type { BuildLineageDeps } from "../../../src/lineage/conference/buildLineage.js";
import { buildDeep } from "../../../src/lineage/deep/buildDeepLineage.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "fixtures");
const SEED_PAPER_ID = "1".repeat(40);

class FakeCompleteJsonProvider implements LLMProvider {
  readonly name = "fake";
  enabled = true;
  batchSize = 1;
  async evaluateBatch(): Promise<(PaperEvaluation | null)[]> {
    return [];
  }
  async chat(): Promise<string | null> {
    return null;
  }
  async classifyRelation(): Promise<RelationClassification | null> {
    return null;
  }
  async completeJson(_system: string, user: string): Promise<string | null> {
    if (user.includes("Parent Paper")) {
      return JSON.stringify({ relation: "extends", confidence: 0.6, rationale: "" });
    }
    if (user.includes("Child Paper")) {
      return JSON.stringify({
        relation: "successor",
        confidence: 0.5,
        rationale: "十分に長い具体的な論文固有の根拠文です。",
      });
    }
    throw new Error(`unexpected prompt: ${user}`);
  }
}

const RESPONSES: Record<string, { status: number; body: unknown }> = {
  "https://api.semanticscholar.org/graph/v1/paper/arXiv:2602.18473": {
    status: 200,
    body: {
      paperId: "S2FOCUS",
      title: "Deep Focus Paper",
      year: 2026,
      venue: "arXiv",
      citationCount: 0,
      authors: [{ name: "A. Author" }],
      abstract: "Focus abstract.",
      externalIds: { ArXiv: "2602.18473" },
    },
  },
  "https://api.semanticscholar.org/graph/v1/paper/S2FOCUS/references": {
    status: 200,
    body: {
      data: [
        {
          citedPaper: {
            paperId: "S2PARENT",
            title: "Parent Paper",
            year: 2020,
            venue: "NeurIPS",
            citationCount: 100,
            authors: [{ name: "B. Author" }],
            abstract: "Parent abstract.",
            externalIds: {},
          },
          isInfluential: true,
          intents: ["methodology"],
        },
      ],
    },
  },
  "https://api.semanticscholar.org/graph/v1/paper/S2FOCUS/citations": {
    status: 200,
    body: {
      data: [
        {
          citingPaper: {
            paperId: "S2CHILD",
            title: "Child Paper",
            year: 2027,
            venue: "ICML",
            citationCount: 3,
            authors: [{ name: "C. Author" }],
            abstract: "Child abstract.",
            externalIds: {},
          },
          isInfluential: true,
          intents: ["result"],
        },
      ],
    },
  },
};

let tmpDirs: string[] = [];
afterEach(() => {
  for (const dir of tmpDirs) rmSync(dir, { recursive: true, force: true });
  tmpDirs = [];
});

function makeDeps(): BuildLineageDeps {
  const cacheDir = mkdtempSync(join(tmpdir(), "build-deep-cache-"));
  tmpDirs.push(cacheDir);
  return {
    cacheDir,
    sleep: async () => {},
    fetchImpl: async (url: string) => {
      const base = url.split("?")[0]!;
      const entry = RESPONSES[base];
      if (!entry) throw new Error(`no canned response for url=${JSON.stringify(base)}`);
      return { status: entry.status, json: async () => entry.body };
    },
  };
}

describe("buildDeep() parity: slot-fill fallback on an empty LLM rationale (LIN-36)", () => {
  it("matches the real Python builder's output structurally (generated_at excluded)", async () => {
    const expected = JSON.parse(
      readFileSync(join(FIXTURES, "build_deep_happy.expected.json"), "utf8"),
    );
    const deps = makeDeps();
    const result = await buildDeep(
      "2602.18473",
      {
        seedPaperId: SEED_PAPER_ID,
        depth: 1,
        topParents: 5,
        topChildren: 5,
        venueOverride: "ICLR 2026",
        tierOverride: "A+",
        provider: new FakeCompleteJsonProvider(),
        rateDelayMs: 0,
        generatedAtOverride: "FIXED",
      },
      deps,
    );
    expect(result).toEqual(expected);
  });
});
