/**
 * Parity harness (design doc §7.2) for `generateManifest`/`writeManifest`
 * (TS port of `paperpilot/scripts/generate_deep_manifest.py`).
 *
 * Fixtures were generated by running the real Python builder under
 * `uv run --extra dev python -m paperpilot.scripts.generate_deep_manifest
 * --docs-dir <tmp>/conf` on a copy of the input files (always named `conf`,
 * since the manifest's `conference` field is the docs-dir basename), and are
 * committed so this test does not depend on Python being installed to run.
 *
 * - `positive/`: a synthetic `lineage-artifact-v1` deep artifact whose
 *   identity (filename arXiv id / `meta.arxiv_id` / `meta.seed_paper_id` /
 *   root focus aliases / catalog paper_id+arXiv pair) resolves exactly —
 *   exercises the one-entry path.
 * - `legacy-noop/`: a real currently-published deep artifact (pre-v1 schema,
 *   `docs/iclr-2026/deep-1706.03762.json`) plus its real `papers.json` —
 *   exercises the all-skipped, zero-entry path, which is every deep artifact
 *   on the real site today (see `docs/design/09-implementation-status.md`:
 *   "deep tree 14 本はビューアへの導線が無く orphan").
 */
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { generateManifest } from "../../../src/lineage/deep/generateDeepManifest.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "fixtures");

let tmpDirs: string[] = [];
afterEach(() => {
  for (const dir of tmpDirs) rmSync(dir, { recursive: true, force: true });
  tmpDirs = [];
});

function materializeFixture(name: string): string {
  const inputDir = join(FIXTURES, name, "input");
  const tmp = mkdtempSync(join(tmpdir(), "deep-manifest-"));
  const confDir = join(tmp, "conf");
  const { mkdirSync } = require("node:fs") as typeof import("node:fs");
  mkdirSync(confDir);
  for (const file of readdirSync(inputDir)) {
    writeFileSync(join(confDir, file), readFileSync(join(inputDir, file)));
  }
  tmpDirs.push(tmp);
  return confDir;
}

describe.each(["positive", "legacy-noop"])("generateManifest parity: %s", (name) => {
  it("matches the real Python builder's output", () => {
    const confDir = materializeFixture(name);
    const expected = JSON.parse(
      readFileSync(join(FIXTURES, name, "expected.deep-manifest.json"), "utf8"),
    );
    const actual = generateManifest(confDir);
    expect(actual).toEqual(expected);
  });
});
