/**
 * `themeSlug` unit tests, plus the 3-way parity pin
 * docs/migration/p4-followups.md #25 asks for: this consolidated
 * `packages/core` implementation vs `worker/slug.js`'s `themeSlug()`
 * (dynamically imported, left untouched — it is production code until
 * P5) vs the real Python `theme_slug()` (via a committed fixture
 * generated by `fixtures/gen.py`, the same pattern
 * `packages/core/test/pycompat/fixtures/gen.py` uses).
 */
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { themeSlug } from "../../src/slug/theme.js";
import themeSlugCases from "./fixtures/theme-slug-cases.json" with { type: "json" };

const here = dirname(fileURLToPath(import.meta.url));
const WORKER_SLUG_JS = resolve(here, "../../../../worker/slug.js");

describe("themeSlug", () => {
  // Expected outputs independently derived from the documented
  // algorithm (NFKD -> ASCII-only -> lowercase -> collapse non
  // [a-z0-9] runs to "-" -> trim hyphens -> cap 64 + trim).
  const cases: [string, string][] = [
    ["Mixture of Experts", "mixture-of-experts"],
    ["Direct-Preference-Optimization", "direct-preference-optimization"],
    ["Vision_Transformer", "vision-transformer"],
    ["Vision    Transformer", "vision-transformer"],
    ["  Diffusion Model  ", "diffusion-model"],
    ["RLHF", "rlhf"],
    ["BERT 2018", "bert-2018"],
    ["Reinforcement Learning from Human Feedback", "reinforcement-learning-from-human-feedback"],
    ["Retrieval-Augmented Generation", "retrieval-augmented-generation"],
    ["../../etc/passwd", "etc-passwd"],
    ["MoE モデル", "moe"],
  ];

  it.each(cases)("%s -> %s", (input, expected) => {
    expect(themeSlug(input)).toBe(expected);
  });

  it("caps at 64 chars and trims a trailing hyphen left by the cut", () => {
    const slug = themeSlug("a".repeat(200));
    expect(slug.length).toBeLessThanOrEqual(64);
    expect(slug).toBe("a".repeat(64));
    expect(slug.endsWith("-")).toBe(false);
  });

  it("rejects empty / whitespace-only input", () => {
    expect(() => themeSlug("")).toThrow(RangeError);
    expect(() => themeSlug("   ")).toThrow(RangeError);
  });

  it("rejects input that collapses to an empty slug (pure CJK, no ASCII fallback)", () => {
    expect(() => themeSlug("モデル")).toThrow(RangeError);
  });
});

describe("themeSlug 3-way parity (packages/core <-> worker/slug.js <-> Python)", () => {
  it("agrees with worker/slug.js's themeSlug() on every probe input", async () => {
    const workerModule = (await import(WORKER_SLUG_JS)) as {
      themeSlug: (label: string) => string;
    };
    for (const { input, slug, error } of themeSlugCases as Array<{
      input: string;
      slug: string | null;
      error: boolean;
    }>) {
      if (error) {
        expect(() => themeSlug(input), `themeSlug(${JSON.stringify(input)})`).toThrow();
        expect(
          () => workerModule.themeSlug(input),
          `worker themeSlug(${JSON.stringify(input)})`,
        ).toThrow();
      } else {
        expect(themeSlug(input), `themeSlug(${JSON.stringify(input)})`).toBe(slug);
        expect(workerModule.themeSlug(input), `worker themeSlug(${JSON.stringify(input)})`).toBe(
          slug,
        );
      }
    }
  });

  it("agrees with the real Python theme_slug() on every probe input (fixtures/gen.py)", () => {
    for (const { input, slug, error } of themeSlugCases as Array<{
      input: string;
      slug: string | null;
      error: boolean;
    }>) {
      if (error) {
        expect(() => themeSlug(input), `themeSlug(${JSON.stringify(input)})`).toThrow();
      } else {
        expect(themeSlug(input), `themeSlug(${JSON.stringify(input)})`).toBe(slug);
      }
    }
  });
});

it("worker/slug.js itself is untouched by this consolidation (still exports its own themeSlug)", () => {
  const src = readFileSync(WORKER_SLUG_JS, "utf-8");
  expect(src).toContain("export function themeSlug(label)");
});
