"""Generate docs/sitemap.xml from the HTML pages that actually exist.

The sitemap used to be hand-maintained and drifted: it listed 6 URLs while
16 pages existed, so eight conference catalogues (~23,000 of the 28,300
papers) plus `eccv-2024/lineage.html` were absent (#367). Nothing generated
it, so every conference added through `scaffold_conference_page.py` /
`conference-on-demand.yml` silently missed it.

Design decisions carried over from the hand-written file:

* Lineage/deep/theme routes are listed only when their strict
  `lineage-quality-v1` rows are `ready` + `passed`; missing or malformed
  quality metadata excludes every lineage route.
* No `<priority>` / `<changefreq>` — search engines ignore both.
* `404.html` is excluded (it is the SPA fallback, served with HTTP 404).
* Generated `paper-links.html` no-JS fallbacks are `noindex` duplicate views
  of each canonical conference catalog and are excluded.
* Content-addressed paper-slide deck HTML is excluded until promotion exposes
  a verified-manifest-driven list of current revisions. Filesystem discovery
  must not publish stale or unverified deck revisions as canonical URLs.
* No `robots.txt` reference: on a GitHub Pages *project* site, crawlers read
  only the domain-root robots.txt, which GitHub owns. The sitemap has to be
  submitted manually in Search Console.

Usage::

    uv run python -m paperpilot.scripts.build_sitemap            # rewrite
    uv run python -m paperpilot.scripts.build_sitemap --check    # verify only
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from xml.etree import ElementTree

from paperpilot.scripts._lineage_contract import validate_lineage_quality_manifest

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_ROOT = REPO_ROOT / "docs"
SITEMAP = DOCS_ROOT / "sitemap.xml"
QUALITY_MANIFEST = DOCS_ROOT / "lineage-quality-v1.json"
BASE_URL = "https://taichiiiiiiii.github.io/automatic-paper-search/"

#: Pages deliberately kept out of the sitemap.
EXCLUDED = {"404.html"}
PAPER_SLIDE_DECK_PREFIX = "paper-slides-v1/decks/"


def _reject_json_constant(value: str) -> None:
    """Reject NaN/Infinity extensions so Python matches JSON.parse()."""

    raise ValueError(f"non-JSON constant: {value}")


def _eligible_lineage_routes(
    quality_manifest: Path = QUALITY_MANIFEST,
) -> set[str]:
    """Return quality-authorised HTML routes, or an empty set on any drift.

    Sitemap discovery is a publication boundary.  A malformed, missing or
    internally inconsistent quality read model therefore fails closed instead
    of falling back to filesystem presence.
    """

    try:
        payload = json.loads(
            quality_manifest.read_text(encoding="utf-8"),
            parse_constant=_reject_json_constant,
        )
    except (OSError, json.JSONDecodeError, ValueError):
        return set()
    if validate_lineage_quality_manifest(payload):
        return set()

    collections = payload["collections"]

    routes: set[str] = set()
    for row in collections:
        if row["availability"] != "ready" or row["audit_status"] != "passed":
            continue
        kind = row["kind"]
        slug = row["slug"]
        if kind == "conference":
            routes.add(f"{slug}/lineage.html")
        elif kind == "theme":
            routes.add("themes/index.html")
        elif kind == "deep":
            routes.add(f"{row['conference']}/deep.html")
    return routes


def is_excluded(relative_path: str, *, eligible_lineage_routes: set[str] | None = None) -> bool:
    """Return whether one HTML path is intentionally absent from the sitemap."""

    lineage_routes = (
        _eligible_lineage_routes() if eligible_lineage_routes is None else eligible_lineage_routes
    )
    is_lineage_route = relative_path == "themes/index.html" or relative_path.endswith(
        ("/lineage.html", "/deep.html")
    )
    return (
        relative_path in EXCLUDED
        or relative_path.endswith("/paper-links.html")
        or (relative_path.startswith(PAPER_SLIDE_DECK_PREFIX) and relative_path.endswith(".html"))
        or (is_lineage_route and relative_path not in lineage_routes)
    )


HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by paperpilot/scripts/build_sitemap.py. Do not hand-edit: run
     the script after adding a page, and its check mode fails when this file
     and docs/ disagree (#367).

     NOTE: XML forbids a double hyphen inside a comment, so option flags are
     spelled out here rather than written literally.

     On a GitHub Pages project site, robots.txt at the repo path is ignored
     (crawlers read only the domain-root one, which GitHub owns), so this
     sitemap has no robots.txt Sitemap: reference and must be submitted
     manually in Search Console. Lineage, deep and theme routes are listed
     only while the strict quality manifest authorises them. Theme query
     variants share themes/index.html and are never listed separately.
     No priority/changefreq elements — search engines ignore them. -->
<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">
"""
FOOTER = "</urlset>\n"


def page_paths(docs_root: Path = DOCS_ROOT) -> list[str]:
    """Site-relative URLs for every published HTML page, sorted.

    `index.html` collapses to its directory (`iclr-2026/index.html` →
    `iclr-2026/`) so the canonical URL is the directory form, matching the
    links the site itself uses.
    """
    quality_manifest = docs_root / "lineage-quality-v1.json"
    eligible_lineage_routes = _eligible_lineage_routes(quality_manifest)
    urls: set[str] = set()
    for path in docs_root.rglob("*.html"):
        rel = path.relative_to(docs_root).as_posix()
        if is_excluded(rel, eligible_lineage_routes=eligible_lineage_routes):
            continue
        urls.add(rel[: -len("index.html")] if rel.endswith("index.html") else rel)
    # "" is the landing page; sort it first, then the rest alphabetically.
    return sorted(urls, key=lambda u: (u != "", u))


def render(urls: list[str]) -> str:
    body = "".join(f"  <url><loc>{BASE_URL}{u}</loc></url>\n" for u in urls)
    return HEADER + body + FOOTER


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if sitemap.xml does not match docs/ (writes nothing)",
    )
    args = parser.parse_args(argv)

    expected = render(page_paths())
    # Parse before trusting the template. The first version of this header
    # embedded a literal `-` `-check`, which XML forbids inside a comment;
    # the string comparison below happily reported "up to date" for a file
    # no XML parser could read (#367).
    ElementTree.fromstring(expected)
    current = SITEMAP.read_text(encoding="utf-8") if SITEMAP.exists() else ""

    if args.check:
        if current == expected:
            print(f"sitemap.xml is up to date ({len(page_paths())} URLs).")
            return 0
        print(
            "sitemap.xml is out of date. Run "
            "`uv run python -m paperpilot.scripts.build_sitemap` to regenerate.",
            file=sys.stderr,
        )
        return 1

    SITEMAP.write_text(expected, encoding="utf-8")
    print(f"wrote {SITEMAP.relative_to(REPO_ROOT)} ({len(page_paths())} URLs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
