"""Generate docs/sitemap.xml from the HTML pages that actually exist.

The sitemap used to be hand-maintained and drifted: it listed 6 URLs while
16 pages existed, so eight conference catalogues (~23,000 of the 28,300
papers) plus `eccv-2024/lineage.html` were absent (#367). Nothing generated
it, so every conference added through `scaffold_conference_page.py` /
`conference-on-demand.yml` silently missed it.

Design decisions carried over from the hand-written file:

* `themes/?theme=<slug>` views all render `themes/index.html`, so the theme
  gallery contributes exactly one URL rather than one per theme.
* No `<priority>` / `<changefreq>` — search engines ignore both.
* `404.html` is excluded (it is the SPA fallback, served with HTTP 404).
* No `robots.txt` reference: on a GitHub Pages *project* site, crawlers read
  only the domain-root robots.txt, which GitHub owns. The sitemap has to be
  submitted manually in Search Console.

Usage::

    uv run python -m paperpilot.scripts.build_sitemap            # rewrite
    uv run python -m paperpilot.scripts.build_sitemap --check    # verify only
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from xml.etree import ElementTree

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_ROOT = REPO_ROOT / "docs"
SITEMAP = DOCS_ROOT / "sitemap.xml"
BASE_URL = "https://taichiiiiiiii.github.io/automatic-paper-search/"

#: Pages deliberately kept out of the sitemap.
EXCLUDED = {"404.html"}

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by paperpilot/scripts/build_sitemap.py. Do not hand-edit: run
     the script after adding a page, and its check mode fails when this file
     and docs/ disagree (#367).

     NOTE: XML forbids a double hyphen inside a comment, so option flags are
     spelled out here rather than written literally.

     On a GitHub Pages project site, robots.txt at the repo path is ignored
     (crawlers read only the domain-root one, which GitHub owns), so this
     sitemap has no robots.txt Sitemap: reference and must be submitted
     manually in Search Console. The themes ?theme=<slug> views share
     themes/index.html (one URL) and are reachable via the in-page gallery,
     so they are not listed separately. No priority/changefreq elements —
     search engines ignore them. -->
<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">
"""
FOOTER = "</urlset>\n"


def page_paths(docs_root: Path = DOCS_ROOT) -> list[str]:
    """Site-relative URLs for every published HTML page, sorted.

    `index.html` collapses to its directory (`iclr-2026/index.html` →
    `iclr-2026/`) so the canonical URL is the directory form, matching the
    links the site itself uses.
    """
    urls: set[str] = set()
    for path in docs_root.rglob("*.html"):
        rel = path.relative_to(docs_root).as_posix()
        if rel in EXCLUDED:
            continue
        urls.add(rel[: -len("index.html")] if rel.endswith("index.html") else rel)
    # "" is the landing page; sort it first, then the rest alphabetically.
    return sorted(urls, key=lambda u: (u != "", u))


def render(urls: list[str]) -> str:
    body = "".join(f"  <url><loc>{BASE_URL}{u}</loc></url>\n" for u in urls)
    return HEADER + body + FOOTER


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if sitemap.xml does not match docs/ (writes nothing)",
    )
    args = parser.parse_args(argv)

    expected = render(page_paths())
    # Parse before trusting the template. The first version of this header
    # embedded a literal `-` `-check`, which XML forbids inside a comment;
    # the string comparison below happily reported "up to date" for a file
    # no XML parser could read (#367).
    ElementTree.fromstring(expected)
    current = SITEMAP.read_text(encoding="utf-8") if SITEMAP.exists() else ""

    if args.check:
        if current == expected:
            print(f"sitemap.xml is up to date ({len(page_paths())} URLs).")
            return 0
        print(
            "sitemap.xml is out of date. Run "
            "`uv run python -m paperpilot.scripts.build_sitemap` to regenerate.",
            file=sys.stderr,
        )
        return 1

    SITEMAP.write_text(expected, encoding="utf-8")
    print(f"wrote {SITEMAP.relative_to(REPO_ROOT)} ({len(page_paths())} URLs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
