"""Regenerate ``docs/<conf>/deep-manifest.json`` from filesystem state.

The manifest lets ``docs/<conf>/deep.html`` know which ``deep-<arxiv_id>.json``
files exist so it can populate the paper selector.

It is generated by globbing ``deep-*.json`` rather than being written
inline by ``build_deep_lineage.py`` so that multiple concurrent builds
can't race on a shared file. After one or more ``build_deep_lineage.py``
runs, call::

    python paperpilot/scripts/generate_deep_manifest.py --docs-dir docs/iclr-2026

Each entry: ``{arxiv_id, title, filename}``, sorted by ``arxiv_id``
ascending. If ``meta.arxiv_id`` is missing from a deep file, we fall
back to the arxiv id embedded in the filename (``deep-<id>.json``).
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path
from typing import TypedDict

_log = logging.getLogger(__name__)

_FILENAME_RE = re.compile(r"^deep-(?P<id>[^/\\]+)\.json$")
# arXiv id format: YYYY.NNNNN with optional version suffix.
# Enforced so the id is safe to splice into a fetch URL client-side.
_ARXIV_RE = re.compile(r"^\d{4}\.\d{4,5}(v\d+)?$")
_MANIFEST_NAME = "deep-manifest.json"


def _valid_arxiv(s: object) -> str | None:
    return s if isinstance(s, str) and _ARXIV_RE.match(s) else None


class ManifestEntry(TypedDict):
    arxiv_id: str
    title: str
    filename: str


def _entry_from_file(path: Path) -> ManifestEntry | None:
    """Build a manifest entry from one deep-<id>.json, or return None to skip."""
    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        _log.warning("skip %s: unreadable (%s)", path.name, exc)
        return None

    meta = payload.get("meta") if isinstance(payload, dict) else None
    meta_id = meta.get("arxiv_id") if isinstance(meta, dict) else None

    # Fall back to filename-derived id when meta is missing / malformed.
    fname_id: str | None = None
    m = _FILENAME_RE.match(path.name)
    if m:
        fname_id = m.group("id")

    arxiv_id = _valid_arxiv(meta_id) or _valid_arxiv(fname_id)
    if arxiv_id is None:
        _log.warning("skip %s: no valid arxiv_id in meta or filename", path.name)
        return None

    nodes = payload.get("nodes") if isinstance(payload, dict) else None
    title = ""
    if isinstance(nodes, list):
        root_id = payload.get("root") if isinstance(payload, dict) else None
        focus = None
        for n in nodes:
            if not isinstance(n, dict):
                continue
            if n.get("id") == root_id or n.get("is_focus"):
                focus = n
                break
        if focus is None and nodes:
            focus = nodes[0] if isinstance(nodes[0], dict) else None
        if isinstance(focus, dict):
            t = focus.get("title")
            if isinstance(t, str):
                title = t

    return ManifestEntry(arxiv_id=arxiv_id, title=title, filename=path.name)


def generate_manifest(docs_dir: Path) -> list[ManifestEntry]:
    """Scan ``docs_dir`` for ``deep-<id>.json`` files, return sorted entries.

    Ignores ``deep-manifest.json`` itself plus any non-matching files.
    """
    if not docs_dir.is_dir():
        return []

    entries: list[ManifestEntry] = []
    for path in sorted(docs_dir.glob("deep-*.json")):
        if path.name == _MANIFEST_NAME:
            continue
        entry = _entry_from_file(path)
        if entry is not None:
            entries.append(entry)

    entries.sort(key=lambda e: e["arxiv_id"])
    return entries


def write_manifest(docs_dir: Path) -> Path:
    """Generate manifest entries and write ``deep-manifest.json``.

    Returns the path written. Use :func:`generate_manifest` if you need
    the entries directly without a filesystem round-trip.
    """
    docs_dir.mkdir(parents=True, exist_ok=True)
    entries = generate_manifest(docs_dir)
    out = docs_dir / _MANIFEST_NAME
    out.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--docs-dir",
        required=True,
        help="Conference viewer dir (e.g. docs/iclr-2026)",
    )
    args = ap.parse_args(argv)

    docs_dir = Path(args.docs_dir)
    if not docs_dir.is_dir():
        print(f"error: {docs_dir} does not exist or is not a directory", file=sys.stderr)
        return 1

    entries = generate_manifest(docs_dir)
    out = docs_dir / _MANIFEST_NAME
    out.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n")
    print(f"✓ Wrote {out} ({len(entries)} entries)")
    for e in entries:
        print(f"    {e['arxiv_id']:12s}  {e['title'][:60]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
