"""Regenerate ``docs/themes-manifest.json`` from filesystem state.

The manifest lets ``docs/themes/index.html`` know which theme lineage
trees exist so it can populate the picker. It is generated by globbing
``themes/<slug>/lineage.json`` rather than written inline by
``build_theme_lineage.py`` so concurrent builds can't race on a shared
file. After one or more ``build_theme_lineage.py`` runs::

    python -m paperpilot.scripts.generate_themes_manifest --themes-dir docs/themes

Each entry::

    {slug, theme, generated_at, paper_count, year_range}

Sorted by ``slug`` ascending. ``year_range`` is ``[min_year, max_year]``
when at least one node has a year, ``None`` otherwise.

Per security review M3: edges with ``rel`` values outside the allowed
classification enum cause the entire theme to be skipped. This blocks a
malicious commit from poisoning the lineage cache via a fabricated
relation type.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path
from typing import Any, TypedDict

_log = logging.getLogger(__name__)

_MANIFEST_NAME = "themes-manifest.json"
_LINEAGE_NAME = "lineage.json"
# Same character class enforced by theme.js's SLUG_RE — keep in sync with
# paperpilot/scripts/_common.theme_slug() output.
_SLUG_RE = re.compile(r"^[a-z0-9-]+$")
# Mirror of llm/base.py CLASSIFY_SYSTEM_PROMPT relation enum.
_ALLOWED_RELATIONS: frozenset[str] = frozenset(
    {
        "supersedes",
        "successor",
        "extends",
        "ablation",
        "baseline_only",
        "contrasts",
        "unrelated",
    }
)


class ManifestEntry(TypedDict):
    slug: str
    theme: str
    generated_at: str
    paper_count: int
    year_range: list[int] | None


def _validate_edges(edges: Any) -> bool:
    """Return False if any edge has a ``rel`` outside the allowed enum.

    Empty list / non-list ⇒ no edges to validate ⇒ True. This intentionally
    accepts files with zero edges so a freshly generated theme with no
    classified relations is still listed in the manifest.
    """
    if not isinstance(edges, list):
        return True
    for e in edges:
        if not isinstance(e, dict):
            continue
        rel = e.get("rel")
        if rel is not None and rel not in _ALLOWED_RELATIONS:
            return False
    return True


def _entry_from_file(path: Path) -> ManifestEntry | None:
    """Build a manifest entry from one ``themes/<slug>/lineage.json``.

    Returns None when the file is unreadable, has invalid JSON, contains
    forbidden relation values, or yields a slug that doesn't match the
    client's SLUG_RE (which would block the URL-param fetch anyway).
    """
    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        _log.warning("skip %s: unreadable (%s)", path, exc)
        return None
    if not isinstance(payload, dict):
        _log.warning("skip %s: payload is not an object", path)
        return None

    if not _validate_edges(payload.get("edges")):
        _log.warning("skip %s: contains relation outside allowed enum", path)
        return None

    meta = payload.get("meta") if isinstance(payload, dict) else None
    meta = meta if isinstance(meta, dict) else {}

    # Prefer meta.slug (richer source) but reject if it doesn't satisfy the
    # client-side regex. Fall back to the parent directory name, which is
    # filesystem-derived and trusted.
    meta_slug = meta.get("slug")
    if isinstance(meta_slug, str) and _SLUG_RE.match(meta_slug):
        slug = meta_slug
    else:
        dir_slug = path.parent.name
        if not _SLUG_RE.match(dir_slug):
            _log.warning("skip %s: directory name %r is not a valid slug", path, dir_slug)
            return None
        slug = dir_slug

    theme = meta.get("theme")
    if not isinstance(theme, str) or not theme.strip():
        # Last-ditch fallback: humanise the slug ("mixture-of-experts" ⇒
        # "Mixture Of Experts"). Better than dropping the entry, since the
        # user can still pick it.
        theme = slug.replace("-", " ").title()

    generated_at = meta.get("generated_at")
    if not isinstance(generated_at, str):
        generated_at = ""

    nodes = payload.get("nodes")
    nodes = nodes if isinstance(nodes, list) else []
    paper_count = sum(1 for n in nodes if isinstance(n, dict))

    years = [
        n["year"] for n in nodes
        if isinstance(n, dict) and isinstance(n.get("year"), int)
    ]
    year_range: list[int] | None = [min(years), max(years)] if years else None

    return ManifestEntry(
        slug=slug,
        theme=theme,
        generated_at=generated_at,
        paper_count=paper_count,
        year_range=year_range,
    )


def generate_manifest(themes_dir: Path) -> list[ManifestEntry]:
    """Scan ``themes_dir/<slug>/lineage.json`` files and return sorted entries.

    Files outside an immediate ``<slug>/lineage.json`` layout (e.g. a
    stray ``lineage.json`` directly under ``themes_dir`` or
    ``themes-manifest.json`` itself) are ignored.
    """
    if not themes_dir.is_dir():
        return []

    entries: list[ManifestEntry] = []
    for sub in sorted(p for p in themes_dir.iterdir() if p.is_dir()):
        lineage_path = sub / _LINEAGE_NAME
        if not lineage_path.is_file():
            continue
        entry = _entry_from_file(lineage_path)
        if entry is not None:
            entries.append(entry)

    entries.sort(key=lambda e: e["slug"])
    return entries


def write_manifest(themes_dir: Path) -> Path:
    """Generate manifest entries and write ``themes-manifest.json``."""
    themes_dir.mkdir(parents=True, exist_ok=True)
    entries = generate_manifest(themes_dir)
    out = themes_dir / _MANIFEST_NAME
    out.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--themes-dir",
        required=True,
        help="Top-level themes directory (e.g. docs/themes).",
    )
    args = ap.parse_args(argv)

    themes_dir = Path(args.themes_dir)
    if not themes_dir.is_dir():
        print(
            f"error: {themes_dir} does not exist or is not a directory",
            file=sys.stderr,
        )
        return 1

    out = write_manifest(themes_dir)
    entries = json.loads(out.read_text())
    print(f"✓ Wrote {out} ({len(entries)} entries)")
    for e in entries:
        rng = e.get("year_range")
        rng_str = f"{rng[0]}-{rng[1]}" if rng else "no-year"
        print(
            f"    {e['slug']:30s}  {e['paper_count']:>4d} papers  {rng_str:>9s}  "
            f"{e['theme'][:40]}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
