/**
 * `marker <out-dir>` — p5-plan.md §2 A4. Writes `_paperpilot-deployment.json`
 * byte-identical to the Python one-liner in
 * `.github/workflows/pages-release.yml`'s "Write deterministic deployment
 * marker" step:
 *
 * ```python
 * marker = {
 *     "schema_version": "paperpilot-deployment-v1",
 *     "source_sha": os.environ["SOURCE_SHA"],
 *     "release_kind": os.environ["RELEASE_KIND"],
 *     "request_id": os.environ["REQUEST_ID"] or None,
 * }
 * Path("docs/_paperpilot-deployment.json").write_text(
 *     json.dumps(marker, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
 *     encoding="utf-8",
 * )
 * ```
 *
 * `json.dumps(..., sort_keys=True, separators=(",", ":"))` on this fixed
 * 4-key dict is reproduced here by hand (not a generic JSON
 * stringifier) because the three env values this module accepts are all
 * regex-validated to a narrow ASCII charset first (see the `_RE`
 * constants below), so `JSON.stringify` on each individual value is
 * guaranteed to match Python's escaping byte-for-byte — no quote,
 * backslash, control character, or non-ASCII byte can reach either
 * encoder. `test/release/fixtures/marker-*.json` were generated by
 * running the exact Python snippet above once (recorded in this
 * changeset's handback) and are compared byte-for-byte, not just
 * value-for-value, in `marker.test.ts`.
 */
import { readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export class MarkerError extends Error {}

const SHA_RE = /^[0-9a-f]{40}$/;
const RELEASE_KIND_RE = /^(normal|rollback)$/;
// Matches the validate job's own `REQUEST_ID` regex in pages-release.yml.
const REQUEST_ID_RE = /^[A-Za-z0-9._:-]{1,128}$/;

export interface MarkerInput {
  sourceSha: string;
  releaseKind: string;
  /** Raw env value: `""` means "no request id" (becomes JSON `null`), matching the Python `os.environ["REQUEST_ID"] or None`. */
  requestId: string;
}

function validateMarkerInput(input: MarkerInput): {
  sourceSha: string;
  releaseKind: string;
  requestId: string | null;
} {
  if (!SHA_RE.test(input.sourceSha)) {
    throw new MarkerError("SOURCE_SHA must be 40 lowercase hex characters");
  }
  if (!RELEASE_KIND_RE.test(input.releaseKind)) {
    throw new MarkerError("RELEASE_KIND must be normal or rollback");
  }
  if (input.requestId !== "" && !REQUEST_ID_RE.test(input.requestId)) {
    throw new MarkerError("REQUEST_ID has an invalid format");
  }
  return {
    sourceSha: input.sourceSha,
    releaseKind: input.releaseKind,
    requestId: input.requestId === "" ? null : input.requestId,
  };
}

/**
 * Builds the exact marker JSON text (including the trailing `\n`), with
 * no filesystem access — the pure part of `writeMarker`, factored out so
 * tests can compare the bytes directly against the committed fixtures
 * without needing a temp directory.
 */
export function buildMarkerJson(input: MarkerInput): string {
  const validated = validateMarkerInput(input);
  // Field order is alphabetical by key -- `sort_keys=True`'s effect on
  // this fixed 4-key dict -- spelled out explicitly rather than computed,
  // so a future added field can't silently reorder existing ones.
  const fields: ReadonlyArray<readonly [key: string, value: string | null]> = [
    ["release_kind", validated.releaseKind],
    ["request_id", validated.requestId],
    ["schema_version", "paperpilot-deployment-v1"],
    ["source_sha", validated.sourceSha],
  ];
  const body = fields
    .map(([key, value]) => `${JSON.stringify(key)}:${JSON.stringify(value)}`)
    .join(",");
  return `{${body}}\n`;
}

export interface WriteMarkerInput extends MarkerInput {
  outDir: string;
}

/** Writes `<outDir>/_paperpilot-deployment.json` and returns the path written. */
export function writeMarker(input: WriteMarkerInput): string {
  let stat: ReturnType<typeof statSync>;
  try {
    stat = statSync(input.outDir);
  } catch {
    throw new MarkerError(`out-dir does not exist: ${input.outDir}`);
  }
  if (!stat.isDirectory()) {
    throw new MarkerError(`out-dir does not exist: ${input.outDir}`);
  }
  const json = buildMarkerJson(input);
  const path = join(input.outDir, "_paperpilot-deployment.json");
  writeFileSync(path, json, "utf-8");
  return path;
}

/** Reads back a previously written marker file (used by `smoke --wait-marker` style callers that already have a local copy, and by tests). */
export function readMarkerJson(outDir: string): string {
  return readFileSync(join(outDir, "_paperpilot-deployment.json"), "utf-8");
}
