/**
 * Byte-for-byte parity between `collect_cvf.py` (committed Python fixture,
 * generated by `run_python.py` — never re-run here) and `runCvfMain` for
 * the SAME canned CVF Open Access HTML, under a fixed clock (design doc
 * §7.2).
 *
 * Regenerate the Python side after a behavior change with:
 *   uv run --extra dev python apps/pipeline/test/conference/fixtures/cvf/run_python.py happy apps/pipeline/test/conference/fixtures/cvf/expected/happy
 *   uv run --extra dev python apps/pipeline/test/conference/fixtures/cvf/run_python.py one-detail-fails apps/pipeline/test/conference/fixtures/cvf/expected/one_detail_fails
 */
import { existsSync, mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { runCvfMain } from "../../../../src/conference/cvf/main.js";
import { compareTrees } from "../../../../src/parity/compare-trees.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const LISTING_HTML = readFileSync(join(HERE, "listing.html"), "utf-8");
const DETAIL_XIAO = readFileSync(join(HERE, "detail_xiao.html"), "utf-8");
const DETAIL_LEE = readFileSync(join(HERE, "detail_lee.html"), "utf-8");

function cannedFetch(failLee = false) {
  return async (url: string) => {
    if (url.endsWith("?day=all")) {
      return { status: 200, text: async () => LISTING_HTML, json: async () => ({}) };
    }
    if (url.includes("Xiao_Det_paper")) {
      return { status: 200, text: async () => DETAIL_XIAO, json: async () => ({}) };
    }
    if (url.includes("Lee_Seg_paper")) {
      if (failLee) return { status: 500, text: async () => "", json: async () => ({}) };
      return { status: 200, text: async () => DETAIL_LEE, json: async () => ({}) };
    }
    return { status: 404, text: async () => "", json: async () => ({}) };
  };
}

describe("cvf parity: happy path", () => {
  it("TS output matches the committed Python fixture byte-for-byte", async () => {
    const actualOutDir = mkdtempSync(join(tmpdir(), "cvf-parity-happy-"));
    const rc = await runCvfMain(
      [
        "--conference",
        "cvpr-2025",
        "--venue",
        "CVPR",
        "--cvf-id",
        "CVPR2025",
        "--max-workers",
        "2",
        "--delay-seconds",
        "0",
      ],
      {
        outputRoot: join(actualOutDir, "output"),
        cvf: { fetchImpl: cannedFetch() },
        arxiv: { fetchText: async () => ({ status: 200, text: async () => "" }) },
        now: () => new Date(Date.UTC(2026, 5, 28)),
        print: () => {},
      },
    );
    expect(rc).toBe(0);

    const report = await compareTrees({
      expectedRoot: join(HERE, "expected", "happy", "output"),
      actualRoot: join(actualOutDir, "output"),
    });
    expect(report.equal, JSON.stringify(report, null, 2)).toBe(true);
  });
});

describe("cvf parity: one detail page fails (CNF-03) failure path", () => {
  it("TS exits 1 and writes nothing, matching the Python side's exit code", async () => {
    const actualOutDir = mkdtempSync(join(tmpdir(), "cvf-parity-fail-"));
    const rc = await runCvfMain(
      [
        "--conference",
        "cvpr-2025",
        "--venue",
        "CVPR",
        "--cvf-id",
        "CVPR2025",
        "--max-workers",
        "1",
        "--delay-seconds",
        "0",
      ],
      {
        outputRoot: join(actualOutDir, "output"),
        cvf: { fetchImpl: cannedFetch(true), sleep: async () => {} },
        arxiv: { fetchText: async () => ({ status: 200, text: async () => "" }) },
        now: () => new Date(Date.UTC(2026, 5, 28)),
        print: () => {},
      },
    );

    const expectedManifest = JSON.parse(
      readFileSync(join(HERE, "expected", "one_detail_fails", "manifest.json"), "utf-8"),
    );
    expect(rc).toBe(expectedManifest.exitCode);
    expect(existsSync(join(actualOutDir, "output"))).toBe(false);
  });
});
