/**
 * Parity harness (design doc §7.2) for `build()` (TS port of
 * `build_lineage.py::build`).
 *
 * The fixture was generated by running the real Python `build()` under
 * `uv run --extra dev python apps/pipeline/test/lineage/conference/fixtures/
 * dump_python_build_lineage.py` against a canned S2 response map
 * (`request_with_retry` monkeypatched) and a fake LLM provider whose
 * `classify_relation` always returns `None` — simulating "LLM dark" (the
 * common free-tier-quota steady state), which exercises the
 * `derive_relation(strict_mode="off")` heuristic fallback path. No network;
 * committed so this test does not depend on Python being installed to run.
 */
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import type {
  ClassifyPaperLike,
  LLMProvider,
  PaperEvaluation,
  RelationClassification,
} from "../../../src/collect/llm/provider.js";
import { type BuildLineageDeps, build } from "../../../src/lineage/conference/buildLineage.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "fixtures");
const PAPER_ID_ONE = "1".repeat(40);

class FakeDarkProvider implements LLMProvider {
  readonly name = "fake";
  enabled = true;
  batchSize = 1;
  async evaluateBatch(): Promise<(PaperEvaluation | null)[]> {
    return [];
  }
  async chat(): Promise<string | null> {
    return null;
  }
  async classifyRelation(
    _a: ClassifyPaperLike,
    _b: ClassifyPaperLike,
  ): Promise<RelationClassification | null> {
    return null;
  }
  async completeJson(): Promise<string | null> {
    return null;
  }
}

const RESPONSES: Record<string, { status: number; body: unknown }> = {
  "https://api.semanticscholar.org/graph/v1/paper/arXiv:2601.00001": {
    status: 200,
    body: {
      paperId: "S2FOCUS",
      title: "Oral Paper One",
      year: 2026,
      venue: "arXiv",
      citationCount: 0,
      authors: [{ name: "A. Author" }],
      abstract: "Focus abstract.",
      externalIds: { ArXiv: "2601.00001" },
    },
  },
  "https://api.semanticscholar.org/graph/v1/paper/S2FOCUS/references": {
    status: 200,
    body: {
      data: [
        {
          citedPaper: {
            paperId: "S2PARENT",
            title: "Parent Paper",
            year: 2020,
            venue: "NeurIPS",
            citationCount: 100,
            authors: [{ name: "B. Author" }],
            abstract: "Parent abstract.",
            externalIds: {},
          },
          isInfluential: true,
          intents: ["methodology"],
        },
      ],
    },
  },
  "https://api.semanticscholar.org/graph/v1/paper/S2FOCUS/citations": {
    status: 200,
    body: {
      data: [
        {
          citingPaper: {
            paperId: "S2CHILD",
            title: "Child Paper",
            year: 2027,
            venue: "ICML",
            citationCount: 3,
            authors: [{ name: "C. Author" }],
            abstract: "Child abstract.",
            externalIds: {},
          },
          isInfluential: true,
          intents: ["result"],
        },
      ],
    },
  },
};

let tmpDirs: string[] = [];
afterEach(() => {
  for (const dir of tmpDirs) rmSync(dir, { recursive: true, force: true });
  tmpDirs = [];
});

function makeTmpDocsRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "build-lineage-"));
  tmpDirs.push(root);
  const docsDir = join(root, "docs", "testconf");
  mkdirSync(docsDir, { recursive: true });
  writeFileSync(
    join(docsDir, "papers.json"),
    JSON.stringify([
      {
        paper_id: PAPER_ID_ONE,
        title: "Oral Paper One",
        type: "Oral",
        arxiv_id: "2601.00001",
        tags: ["vision"],
        citation_count: 5,
        github_stars: 2,
      },
    ]),
  );
  return join(root, "docs");
}

function makeDeps(): BuildLineageDeps {
  const cacheDir = mkdtempSync(join(tmpdir(), "build-lineage-cache-"));
  tmpDirs.push(cacheDir);
  return {
    cacheDir,
    sleep: async () => {},
    fetchImpl: async (url: string) => {
      const base = url.split("?")[0]!;
      const entry = RESPONSES[base];
      if (!entry) throw new Error(`no canned response for url=${JSON.stringify(base)}`);
      return { status: entry.status, json: async () => entry.body };
    },
  };
}

describe("build() parity: LLM-dark heuristic fallback path", () => {
  it("matches the real Python builder's output structurally", async () => {
    const expected = JSON.parse(
      readFileSync(join(FIXTURES, "build_lineage_happy.expected.json"), "utf8"),
    );
    const docsRoot = makeTmpDocsRoot();
    const deps = makeDeps();
    const result = await build(
      {
        docsRoot,
        repoRoot: docsRoot,
        conference: "testconf",
        generatedAt: "2026-08-30T00:00:00Z",
        provider: new FakeDarkProvider(),
        rateDelayMs: 0,
      },
      deps,
    );
    expect(result).toEqual(expected);
  });
});
