/**
 * Parity harness (design doc §7.2) for `buildGraph` (TS port of
 * `build_conference_lineage.py::build_graph`).
 *
 * Fixtures were generated by running the real Python builder under
 * `uv run --extra dev python apps/pipeline/test/lineage/conference/fixtures/
 * dump_python_conference_lineage.py` against a canned OpenAlex response map
 * (`request_with_retry` monkeypatched — no network), and are committed so
 * this test does not depend on Python being installed to run. To
 * regenerate after a behavior change, re-run that script and review the
 * diff.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type { HttpResponseLike } from "../../../src/collect/http/requestWithRetry.js";
import {
  buildGraph,
  type OpenAlexDeps,
} from "../../../src/lineage/conference/buildConferenceLineage.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "fixtures");

const PAPER_ID_ONE = "1".repeat(40);

function readExpected(name: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(FIXTURES, `${name}.expected.json`), "utf8"));
}

function filterParam(url: string): string {
  return new URL(url).searchParams.get("filter") ?? "";
}

const HAPPY_RESPONSES: Record<string, { status: number; body: unknown }> = {
  "title.search:Oral Paper One": {
    status: 200,
    body: {
      results: [
        {
          id: "https://openalex.org/W100",
          title: "Oral Paper One",
          publication_year: 2026,
          authorships: [{ author: { display_name: "A. Author" } }],
          primary_location: { source: { display_name: "ICLR" } },
          locations: [],
          ids: { openalex: "https://openalex.org/W100", arxiv: "2601.00001" },
          doi: null,
          referenced_works: ["https://openalex.org/W200"],
          cited_by_count: 10,
        },
      ],
    },
  },
  "ids.openalex:W200": {
    status: 200,
    body: {
      results: [
        {
          id: "https://openalex.org/W200",
          title: "Reference Paper",
          publication_year: 2020,
          authorships: [{ author: { display_name: "B. Author" } }],
          primary_location: { source: { display_name: "NeurIPS" } },
        },
      ],
    },
  },
  "cites:W100": {
    status: 200,
    body: {
      results: [
        {
          id: "https://openalex.org/W300",
          title: "Citer Paper",
          publication_year: 2027,
          authorships: [{ author: { display_name: "C. Author" } }],
          primary_location: { source: { display_name: "ICML" } },
        },
      ],
    },
  },
};

function cannedDeps(responses: Record<string, { status: number; body: unknown }>): OpenAlexDeps {
  return {
    fetchImpl: async (url): Promise<HttpResponseLike> => {
      const filt = filterParam(url);
      const entry = responses[filt];
      if (!entry) throw new Error(`no canned response for filter=${JSON.stringify(filt)}`);
      return { status: entry.status, json: async () => entry.body };
    },
    sleep: async () => {},
  };
}

const ORALS = [
  {
    paper_id: PAPER_ID_ONE,
    title: "Oral Paper One",
    source: "arxiv",
    source_id: "2601.00001",
    arxiv_id: "2601.00001",
  },
];

describe("buildGraph parity: happy path", () => {
  it("matches the real Python builder's output byte-for-byte (structurally)", async () => {
    const { BuildCompleteness } = await import("../../../src/lineage/fetch-state/completeness.js");
    const completeness = new BuildCompleteness();
    const graph = await buildGraph(
      ORALS,
      {
        display: "ICLR 2026",
        refsPer: 4,
        citersPer: 2,
        generatedAt: "2026-08-30T00:00:00Z",
        completeness,
      },
      cannedDeps(HAPPY_RESPONSES),
    );
    expect(graph).toEqual(readExpected("happy"));
  });
});

describe("buildGraph parity: subject failure (LIN-08)", () => {
  it("resolve_oral outage -> empty graph + a recorded subject failure (never thrown from build_graph itself)", async () => {
    const expected = readExpected("subject_failure") as {
      graph: unknown;
      subject_failures: string[];
    };
    const { BuildCompleteness } = await import("../../../src/lineage/fetch-state/completeness.js");
    const completeness = new BuildCompleteness();
    const failingDeps: OpenAlexDeps = {
      fetchImpl: async (): Promise<HttpResponseLike> => ({ status: 503, json: async () => ({}) }),
      sleep: async () => {},
    };
    const graph = await buildGraph(
      ORALS,
      {
        display: "ICLR 2026",
        refsPer: 4,
        citersPer: 2,
        generatedAt: "2026-08-30T00:00:00Z",
        completeness,
      },
      failingDeps,
    );
    expect(graph).toEqual(expected.graph);
    expect(completeness.subjectFailures).toEqual(expected.subject_failures);
    expect(completeness.subjectComplete).toBe(false);
  });
});
