/**
 * Regenerate `docs/themes/themes-manifest.json` from filesystem state —
 * TS port of `paperpilot/scripts/generate_themes_manifest.py`.
 *
 * Generated by globbing `themes/<slug>/lineage.json` (rather than
 * written inline by the theme builder) so concurrent builds can't race
 * on a shared file (CLAUDE.md §14's "並列実行時の race 回避").
 *
 * Safety: edges with `rel` values outside the allowed classification
 * enum cause the entire theme to be skipped (blocks a malicious commit
 * from poisoning the lineage cache via a fabricated relation type).
 */

import { mkdirSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { codepointCompare, pyJsonDumps } from "@paperpilot/core";
import { firstUnusable } from "../../collect/signals/payload.js";
import { atomicWriteText } from "../../collect/state/atomic.js";

const MANIFEST_NAME = "themes-manifest.json";
const LINEAGE_NAME = "lineage.json";

/** Same character class enforced by `theme.js`'s `SLUG_RE` — keep in
 * sync with `themeSlug()`'s output shape. */
const SLUG_RE = /^[a-z0-9-]+$/;

/** Mirror of the relation enum in `llm/base.ts`'s `CLASSIFY_SYSTEM_PROMPT`. */
const ALLOWED_RELATIONS: ReadonlySet<string> = new Set([
  "supersedes",
  "successor",
  "extends",
  "ablation",
  "baseline_only",
  "contrasts",
  "unrelated",
]);

/** An artifact could not be read, so the manifest would be incomplete.
 * Distinct from an artifact read and deliberately excluded (bad slug,
 * forbidden relation): that omission is a decision, this one is a gap. */
export class UnreadableArtifactError extends Error {}

export interface ManifestEntry {
  slug: string;
  theme: string;
  generated_at: string;
  paper_count: number;
  year_range: [number, number] | null;
}

/** `false` if the `edges` block is not one we can judge: an empty list
 * is fine (a freshly generated theme with no classified relations
 * still belongs in the manifest); an absent key, a non-array, a
 * non-object element, or an element without an allowed `rel` is not. */
function validateEdges(edges: unknown): boolean {
  if (!Array.isArray(edges)) return false;
  for (const e of edges) {
    if (e === null || typeof e !== "object" || Array.isArray(e)) return false;
    const rel = (e as Record<string, unknown>).rel;
    if (typeof rel !== "string" || !ALLOWED_RELATIONS.has(rel)) return false;
  }
  return true;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Title-case a slug's hyphen-joined words ("mixture-of-experts" ->
 * "Mixture Of Experts") — the last-ditch fallback when `meta.theme` is
 * missing, matching Python's `str.title()`. */
function titleCaseFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((word) => (word ? word[0]!.toUpperCase() + word.slice(1).toLowerCase() : word))
    .join(" ");
}

export interface GenerateThemesManifestLogger {
  warn: (msg: string) => void;
}

/** Build a manifest entry from one `themes/<slug>/lineage.json`.
 * Returns `null` when the file is structurally invalid in a way that
 * is a DECISION to skip (bad relation enum, bad slug, unreadable nodes
 * block). Throws `UnreadableArtifactError` when the file itself cannot
 * be read/parsed — that is a GAP, not a decision (LIN: an unreadable
 * artifact is almost always a concurrent read of a non-atomic write). */
export function entryFromFile(
  path: string,
  logger?: GenerateThemesManifestLogger,
): ManifestEntry | null {
  let payload: unknown;
  try {
    payload = JSON.parse(readFileSync(path, "utf-8"));
  } catch (exc) {
    throw new UnreadableArtifactError(`${path}: ${String(exc)}`);
  }
  if (!isPlainObject(payload)) {
    logger?.warn(`skip ${path}: payload is not an object`);
    return null;
  }

  if (!validateEdges(payload.edges)) {
    logger?.warn(`skip ${path}: contains relation outside allowed enum`);
    return null;
  }

  const meta = isPlainObject(payload.meta) ? payload.meta : {};

  // Prefer meta.slug (richer source) but reject if it doesn't satisfy
  // the client-side regex. Fall back to the parent directory name
  // (filesystem-derived and trusted).
  const metaSlug = meta.slug;
  let slug: string;
  if (typeof metaSlug === "string" && SLUG_RE.test(metaSlug)) {
    slug = metaSlug;
  } else {
    const dirSlug = path.split("/").slice(-2, -1)[0] ?? "";
    if (!SLUG_RE.test(dirSlug)) {
      logger?.warn(`skip ${path}: directory name ${JSON.stringify(dirSlug)} is not a valid slug`);
      return null;
    }
    slug = dirSlug;
  }

  const metaTheme = meta.theme;
  const theme: string =
    typeof metaTheme === "string" && metaTheme.trim() ? metaTheme : titleCaseFromSlug(slug);

  const generatedAt = typeof meta.generated_at === "string" ? meta.generated_at : "";

  const nodes = payload.nodes;
  // `paper_count` is the number this manifest publishes, so counting
  // elements we cannot read would overstate it; an absent `nodes` key
  // or an unreadable element is not the same as a genuinely empty theme.
  if (
    !Array.isArray(nodes) ||
    firstUnusable(nodes, (n) => isPlainObject(n) && typeof n.id === "string" && Boolean(n.id)) !==
      null
  ) {
    logger?.warn(`skip ${path.split("/").pop()}: nodes block is not readable`);
    return null;
  }
  const paperCount = nodes.length;

  const years: number[] = [];
  for (const n of nodes as Record<string, unknown>[]) {
    const year = n.year;
    if (typeof year === "number" && Number.isInteger(year)) years.push(year);
  }
  const yearRange: [number, number] | null =
    years.length > 0 ? [Math.min(...years), Math.max(...years)] : null;

  return { slug, theme, generated_at: generatedAt, paper_count: paperCount, year_range: yearRange };
}

/** Scan `themesDir/<slug>/lineage.json` files and return sorted entries.
 * Files outside an immediate `<slug>/lineage.json` layout are ignored. */
export function generateManifest(
  themesDir: string,
  logger?: GenerateThemesManifestLogger,
): ManifestEntry[] {
  // LOW (#review): Python's `generate_manifest` returns `[]` only when
  // `not themes_dir.is_dir()` — true for both "doesn't exist" and
  // "exists but is a file", neither of which raises in Python. The
  // previous TS version used a `try { readdirSync(...) } catch { return
  // [] }` around the WHOLE read, which collapsed ANY failure (a
  // permission error, a transient I/O error) into the same empty
  // result — and `writeManifest` writes whatever this returns straight
  // to disk, so a transient failure here could silently overwrite a
  // real, non-empty `themes-manifest.json` with `[]`. Check existence
  // and type first (mirroring `is_dir()` exactly, via a stat that never
  // throws for "missing"); anything else that fails is a real problem
  // and must propagate, not be swallowed as "no themes".
  const themesDirStat = statSync(themesDir, { throwIfNoEntry: false });
  if (themesDirStat === undefined || !themesDirStat.isDirectory()) {
    return [];
  }
  const subdirs = readdirSync(themesDir)
    .filter((name) => {
      try {
        return statSync(join(themesDir, name)).isDirectory();
      } catch {
        return false;
      }
    })
    .sort(codepointCompare);

  const entries: ManifestEntry[] = [];
  const unreadable: string[] = [];
  for (const sub of subdirs) {
    const lineagePath = join(themesDir, sub, LINEAGE_NAME);
    let isFile: boolean;
    try {
      isFile = statSync(lineagePath).isFile();
    } catch {
      isFile = false;
    }
    if (!isFile) continue;
    try {
      const entry = entryFromFile(lineagePath, logger);
      if (entry !== null) entries.push(entry);
    } catch (exc) {
      if (exc instanceof UnreadableArtifactError) {
        unreadable.push(exc.message);
        continue;
      }
      throw exc;
    }
  }

  if (unreadable.length > 0) {
    throw new UnreadableArtifactError(
      `refusing to build a manifest that silently omits ${unreadable.length} unreadable artifact(s):\n  ${unreadable.join("\n  ")}`,
    );
  }

  entries.sort((a, b) => codepointCompare(a.slug, b.slug));
  return entries;
}

/** Generate manifest entries and write `themes-manifest.json`.
 * Throws `UnreadableArtifactError` rather than publishing a manifest
 * that dropped a theme it could not read; the previous manifest stays
 * in place. */
export function writeManifest(themesDir: string, logger?: GenerateThemesManifestLogger): string {
  mkdirSync(themesDir, { recursive: true });
  const entries = generateManifest(themesDir, logger);
  const out = join(themesDir, MANIFEST_NAME);
  atomicWriteText(out, `${pyJsonDumps(entries, { ensureAscii: false, indent: 2 })}\n`);
  return out;
}
